// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudPacker20230101DeleteEnforcedBlockVersionResponse hashicorp cloud packer 20230101 delete enforced block version response
//
// swagger:model hashicorp.cloud.packer_20230101.DeleteEnforcedBlockVersionResponse
type HashicorpCloudPacker20230101DeleteEnforcedBlockVersionResponse any
