// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101UpdateEnforcedBlockVersionBody hashicorp cloud packer 20230101 update enforced block version body
//
// swagger:model hashicorp.cloud.packer_20230101.UpdateEnforcedBlockVersionBody
type HashicorpCloudPacker20230101UpdateEnforcedBlockVersionBody struct {

	// additional description
	AdditionalDescription string `json:"additional_description,omitempty"`

	// update mask
	UpdateMask string `json:"update_mask,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 update enforced block version body
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 update enforced block version body based on context it is used
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101UpdateEnforcedBlockVersionBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
