// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101GetRunTaskConfigResponse hashicorp cloud packer 20230101 get run task config response
//
// swagger:model hashicorp.cloud.packer_20230101.GetRunTaskConfigResponse
type HashicorpCloudPacker20230101GetRunTaskConfigResponse struct {

	// on untracked image
	OnUntrackedImage *HashicorpCloudPacker20230101RunTaskBehaviour `json:"on_untracked_image,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 get run task config response
func (m *HashicorpCloudPacker20230101GetRunTaskConfigResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOnUntrackedImage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101GetRunTaskConfigResponse) validateOnUntrackedImage(formats strfmt.Registry) error {
	if typeutils.IsZero(m.OnUntrackedImage) { // not required
		return nil
	}

	if m.OnUntrackedImage != nil {
		if err := m.OnUntrackedImage.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("on_untracked_image")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("on_untracked_image")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 get run task config response based on the context it is used
func (m *HashicorpCloudPacker20230101GetRunTaskConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOnUntrackedImage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101GetRunTaskConfigResponse) contextValidateOnUntrackedImage(ctx context.Context, formats strfmt.Registry) error {

	if m.OnUntrackedImage != nil {

		if typeutils.IsZero(m.OnUntrackedImage) { // not required
			return nil
		}

		if err := m.OnUntrackedImage.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("on_untracked_image")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("on_untracked_image")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101GetRunTaskConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101GetRunTaskConfigResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101GetRunTaskConfigResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
