// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101UpdateEnforcedBlockBody hashicorp cloud packer 20230101 update enforced block body
//
// swagger:model hashicorp.cloud.packer_20230101.UpdateEnforcedBlockBody
type HashicorpCloudPacker20230101UpdateEnforcedBlockBody struct {

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// update mask
	UpdateMask string `json:"update_mask,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 update enforced block body
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 update enforced block body based on context it is used
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101UpdateEnforcedBlockBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
