// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101BuildMetadata hashicorp cloud packer 20230101 build metadata
//
// swagger:model hashicorp.cloud.packer_20230101.BuildMetadata
type HashicorpCloudPacker20230101BuildMetadata struct {

	// Information about the CICD pipeline.
	Cicd any `json:"cicd,omitempty"`

	// Information about the packer version, plugins, and OS.
	Packer any `json:"packer,omitempty"`

	// Information about the version control system.
	Vcs any `json:"vcs,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 build metadata
func (m *HashicorpCloudPacker20230101BuildMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 build metadata based on context it is used
func (m *HashicorpCloudPacker20230101BuildMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101BuildMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101BuildMetadata) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101BuildMetadata
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
