// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsBody hashicorp cloud packer 20230101 manage enforced block linked buckets body
//
// swagger:model hashicorp.cloud.packer_20230101.ManageEnforcedBlockLinkedBucketsBody
type HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsBody struct {

	// bucket names
	BucketNames []string `json:"bucket_names"`
}

// Validate validates this hashicorp cloud packer 20230101 manage enforced block linked buckets body
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 manage enforced block linked buckets body based on context it is used
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
