// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudPacker20230101DeleteBuildResponse hashicorp cloud packer 20230101 delete build response
//
// swagger:model hashicorp.cloud.packer_20230101.DeleteBuildResponse
type HashicorpCloudPacker20230101DeleteBuildResponse any
