// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101UpdateRegistryBody hashicorp cloud packer 20230101 update registry body
//
// swagger:model hashicorp.cloud.packer_20230101.UpdateRegistryBody
type HashicorpCloudPacker20230101UpdateRegistryBody struct {

	// activated
	Activated bool `json:"activated,omitempty"`

	// feature tier
	FeatureTier *HashicorpCloudPacker20230101RegistryConfigTier `json:"feature_tier,omitempty"`

	// To enable `Activated` field use `update_mask`. Send `["config.activated",]` if you want to activate or deactivate the
	// registry. If given `[]`, we will ignore `activated` entirely.
	UpdateMask string `json:"update_mask,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 update registry body
func (m *HashicorpCloudPacker20230101UpdateRegistryBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeatureTier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101UpdateRegistryBody) validateFeatureTier(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FeatureTier) { // not required
		return nil
	}

	if m.FeatureTier != nil {
		if err := m.FeatureTier.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("feature_tier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("feature_tier")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 update registry body based on the context it is used
func (m *HashicorpCloudPacker20230101UpdateRegistryBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFeatureTier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101UpdateRegistryBody) contextValidateFeatureTier(ctx context.Context, formats strfmt.Registry) error {

	if m.FeatureTier != nil {

		if typeutils.IsZero(m.FeatureTier) { // not required
			return nil
		}

		if err := m.FeatureTier.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("feature_tier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("feature_tier")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateRegistryBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateRegistryBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101UpdateRegistryBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
