// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101ImpactedBuild hashicorp cloud packer 20230101 impacted build
//
// swagger:model hashicorp.cloud.packer_20230101.ImpactedBuild
type HashicorpCloudPacker20230101ImpactedBuild struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 impacted build
func (m *HashicorpCloudPacker20230101ImpactedBuild) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 impacted build based on context it is used
func (m *HashicorpCloudPacker20230101ImpactedBuild) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ImpactedBuild) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ImpactedBuild) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101ImpactedBuild
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
