// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudPacker20230101DeleteChannelResponse hashicorp cloud packer 20230101 delete channel response
//
// swagger:model hashicorp.cloud.packer_20230101.DeleteChannelResponse
type HashicorpCloudPacker20230101DeleteChannelResponse any
