// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101UpdateEnforcedBlockResponse hashicorp cloud packer 20230101 update enforced block response
//
// swagger:model hashicorp.cloud.packer_20230101.UpdateEnforcedBlockResponse
type HashicorpCloudPacker20230101UpdateEnforcedBlockResponse struct {

	// enforced block
	EnforcedBlock *HashicorpCloudPacker20230101EnforcedBlock `json:"enforced_block,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 update enforced block response
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnforcedBlock(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockResponse) validateEnforcedBlock(formats strfmt.Registry) error {
	if typeutils.IsZero(m.EnforcedBlock) { // not required
		return nil
	}

	if m.EnforcedBlock != nil {
		if err := m.EnforcedBlock.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("enforced_block")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("enforced_block")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 update enforced block response based on the context it is used
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEnforcedBlock(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockResponse) contextValidateEnforcedBlock(ctx context.Context, formats strfmt.Registry) error {

	if m.EnforcedBlock != nil {

		if typeutils.IsZero(m.EnforcedBlock) { // not required
			return nil
		}

		if err := m.EnforcedBlock.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("enforced_block")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("enforced_block")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101UpdateEnforcedBlockResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
