// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudPacker20230101TFCArtifactValidationRunTaskResponse === MISC ===
//
// swagger:model hashicorp.cloud.packer_20230101.TFCArtifactValidationRunTaskResponse
type HashicorpCloudPacker20230101TFCArtifactValidationRunTaskResponse any
