// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101ExternalArtifactBucket hashicorp cloud packer 20230101 external artifact bucket
//
// swagger:model hashicorp.cloud.packer_20230101.ExternalArtifactBucket
type HashicorpCloudPacker20230101ExternalArtifactBucket struct {

	// Unique identifier (ULID).
	ID string `json:"id,omitempty"`

	// A key:value map for custom, user-settable metadata about your bucket.
	Labels map[string]string `json:"labels,omitempty"`

	// Human-readable name for the bucket.
	Name string `json:"name,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 external artifact bucket
func (m *HashicorpCloudPacker20230101ExternalArtifactBucket) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 external artifact bucket based on context it is used
func (m *HashicorpCloudPacker20230101ExternalArtifactBucket) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ExternalArtifactBucket) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ExternalArtifactBucket) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101ExternalArtifactBucket
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
