// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101CreateRegistryBody hashicorp cloud packer 20230101 create registry body
//
// swagger:model hashicorp.cloud.packer_20230101.CreateRegistryBody
type HashicorpCloudPacker20230101CreateRegistryBody struct {

	// feature tier
	FeatureTier *HashicorpCloudPacker20230101RegistryConfigTier `json:"feature_tier,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 create registry body
func (m *HashicorpCloudPacker20230101CreateRegistryBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeatureTier(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101CreateRegistryBody) validateFeatureTier(formats strfmt.Registry) error {
	if typeutils.IsZero(m.FeatureTier) { // not required
		return nil
	}

	if m.FeatureTier != nil {
		if err := m.FeatureTier.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("feature_tier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("feature_tier")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 create registry body based on the context it is used
func (m *HashicorpCloudPacker20230101CreateRegistryBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFeatureTier(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101CreateRegistryBody) contextValidateFeatureTier(ctx context.Context, formats strfmt.Registry) error {

	if m.FeatureTier != nil {

		if typeutils.IsZero(m.FeatureTier) { // not required
			return nil
		}

		if err := m.FeatureTier.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("feature_tier")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("feature_tier")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101CreateRegistryBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101CreateRegistryBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101CreateRegistryBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
