// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse hashicorp cloud packer 20230101 manage enforced block linked buckets response
//
// swagger:model hashicorp.cloud.packer_20230101.ManageEnforcedBlockLinkedBucketsResponse
type HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse struct {

	// enforced block buckets
	EnforcedBlockBuckets []*HashicorpCloudPacker20230101EnforcedBlockBucket `json:"enforced_block_buckets"`
}

// Validate validates this hashicorp cloud packer 20230101 manage enforced block linked buckets response
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnforcedBlockBuckets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse) validateEnforcedBlockBuckets(formats strfmt.Registry) error {
	if typeutils.IsZero(m.EnforcedBlockBuckets) { // not required
		return nil
	}

	for i := 0; i < len(m.EnforcedBlockBuckets); i++ {
		if typeutils.IsZero(m.EnforcedBlockBuckets[i]) { // not required
			continue
		}

		if m.EnforcedBlockBuckets[i] != nil {
			if err := m.EnforcedBlockBuckets[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("enforced_block_buckets" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("enforced_block_buckets" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 manage enforced block linked buckets response based on the context it is used
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEnforcedBlockBuckets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse) contextValidateEnforcedBlockBuckets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EnforcedBlockBuckets); i++ {

		if m.EnforcedBlockBuckets[i] != nil {

			if typeutils.IsZero(m.EnforcedBlockBuckets[i]) { // not required
				return nil
			}

			if err := m.EnforcedBlockBuckets[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("enforced_block_buckets" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("enforced_block_buckets" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101ManageEnforcedBlockLinkedBucketsResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
