// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudPacker20230101DeleteVersionResponse hashicorp cloud packer 20230101 delete version response
//
// swagger:model hashicorp.cloud.packer_20230101.DeleteVersionResponse
type HashicorpCloudPacker20230101DeleteVersionResponse any
