// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101ImpactedPackage hashicorp cloud packer 20230101 impacted package
//
// swagger:model hashicorp.cloud.packer_20230101.ImpactedPackage
type HashicorpCloudPacker20230101ImpactedPackage struct {

	// name
	Name string `json:"name,omitempty"`

	// purl
	Purl string `json:"purl,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 impacted package
func (m *HashicorpCloudPacker20230101ImpactedPackage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 impacted package based on context it is used
func (m *HashicorpCloudPacker20230101ImpactedPackage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ImpactedPackage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ImpactedPackage) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101ImpactedPackage
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
