// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101CreateEnforcedBlockBody hashicorp cloud packer 20230101 create enforced block body
//
// swagger:model hashicorp.cloud.packer_20230101.CreateEnforcedBlockBody
type HashicorpCloudPacker20230101CreateEnforcedBlockBody struct {

	// Optional additional description for more detailed documentation
	AdditionalDescription string `json:"additional_description,omitempty"`

	// The actual Packer block configuration content that will be enforced
	BlockContent string `json:"block_content,omitempty"`

	// A key:value map for custom, user-settable metadata about the enforced block
	Labels map[string]string `json:"labels,omitempty"`

	// Human-readable name for the enforced block
	Name string `json:"name,omitempty"`

	// The type of Packer configuration template (HCL2 or JSON)
	TemplateType *HashicorpCloudPacker20230101TemplateType `json:"template_type,omitempty"`

	// Initial version of the enforced block
	Version string `json:"version,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 create enforced block body
func (m *HashicorpCloudPacker20230101CreateEnforcedBlockBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTemplateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101CreateEnforcedBlockBody) validateTemplateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TemplateType) { // not required
		return nil
	}

	if m.TemplateType != nil {
		if err := m.TemplateType.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("template_type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("template_type")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 create enforced block body based on the context it is used
func (m *HashicorpCloudPacker20230101CreateEnforcedBlockBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTemplateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101CreateEnforcedBlockBody) contextValidateTemplateType(ctx context.Context, formats strfmt.Registry) error {

	if m.TemplateType != nil {

		if typeutils.IsZero(m.TemplateType) { // not required
			return nil
		}

		if err := m.TemplateType.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("template_type")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("template_type")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101CreateEnforcedBlockBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101CreateEnforcedBlockBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101CreateEnforcedBlockBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
