// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse hashicorp cloud packer 20230101 update enforced block version response
//
// swagger:model hashicorp.cloud.packer_20230101.UpdateEnforcedBlockVersionResponse
type HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse struct {

	// enforced block version
	EnforcedBlockVersion *HashicorpCloudPacker20230101EnforcedBlockVersion `json:"enforced_block_version,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 update enforced block version response
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnforcedBlockVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse) validateEnforcedBlockVersion(formats strfmt.Registry) error {
	if typeutils.IsZero(m.EnforcedBlockVersion) { // not required
		return nil
	}

	if m.EnforcedBlockVersion != nil {
		if err := m.EnforcedBlockVersion.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("enforced_block_version")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("enforced_block_version")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 update enforced block version response based on the context it is used
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEnforcedBlockVersion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse) contextValidateEnforcedBlockVersion(ctx context.Context, formats strfmt.Registry) error {

	if m.EnforcedBlockVersion != nil {

		if typeutils.IsZero(m.EnforcedBlockVersion) { // not required
			return nil
		}

		if err := m.EnforcedBlockVersion.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("enforced_block_version")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("enforced_block_version")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101UpdateEnforcedBlockVersionResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
