// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101Parent hashicorp cloud packer 20230101 parent
//
// swagger:model hashicorp.cloud.packer_20230101.Parent
type HashicorpCloudPacker20230101Parent struct {

	// The parent bucket name.
	BucketName string `json:"bucket_name,omitempty"`

	// The name of the channel associated with this relationship.
	ChannelName string `json:"channel_name,omitempty"`

	// The version currently assigned to the channel associated with the ancestry
	// relationship.
	ChannelVersion *HashicorpCloudPacker20230101ChannelVersion `json:"channel_version,omitempty"`

	// The parent version fingerprint.
	VersionFingerprint string `json:"version_fingerprint,omitempty"`

	// The parent version ULID.
	VersionID string `json:"version_id,omitempty"`

	// The parent version name.
	VersionName string `json:"version_name,omitempty"`
}

// Validate validates this hashicorp cloud packer 20230101 parent
func (m *HashicorpCloudPacker20230101Parent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChannelVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101Parent) validateChannelVersion(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ChannelVersion) { // not required
		return nil
	}

	if m.ChannelVersion != nil {
		if err := m.ChannelVersion.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("channel_version")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("channel_version")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 parent based on the context it is used
func (m *HashicorpCloudPacker20230101Parent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChannelVersion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101Parent) contextValidateChannelVersion(ctx context.Context, formats strfmt.Registry) error {

	if m.ChannelVersion != nil {

		if typeutils.IsZero(m.ChannelVersion) { // not required
			return nil
		}

		if err := m.ChannelVersion.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("channel_version")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("channel_version")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101Parent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101Parent) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101Parent
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
