// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse hashicorp cloud packer 20230101 get enforced block linked buckets response
//
// swagger:model hashicorp.cloud.packer_20230101.GetEnforcedBlockLinkedBucketsResponse
type HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse struct {

	// linked buckets
	LinkedBuckets []*HashicorpCloudPacker20230101EnforcedBlockLinkedBucket `json:"linked_buckets"`
}

// Validate validates this hashicorp cloud packer 20230101 get enforced block linked buckets response
func (m *HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinkedBuckets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse) validateLinkedBuckets(formats strfmt.Registry) error {
	if typeutils.IsZero(m.LinkedBuckets) { // not required
		return nil
	}

	for i := 0; i < len(m.LinkedBuckets); i++ {
		if typeutils.IsZero(m.LinkedBuckets[i]) { // not required
			continue
		}

		if m.LinkedBuckets[i] != nil {
			if err := m.LinkedBuckets[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("linked_buckets" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("linked_buckets" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 get enforced block linked buckets response based on the context it is used
func (m *HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLinkedBuckets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse) contextValidateLinkedBuckets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.LinkedBuckets); i++ {

		if m.LinkedBuckets[i] != nil {

			if typeutils.IsZero(m.LinkedBuckets[i]) { // not required
				return nil
			}

			if err := m.LinkedBuckets[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("linked_buckets" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("linked_buckets" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101GetEnforcedBlockLinkedBucketsResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
