// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudPacker20230101UpdateBucketBody hashicorp cloud packer 20230101 update bucket body
//
// swagger:model hashicorp.cloud.packer_20230101.UpdateBucketBody
type HashicorpCloudPacker20230101UpdateBucketBody struct {

	// A short description of what this bucket's artifacts are for.
	Description string `json:"description,omitempty"`

	// A key:value map for custom, user-settable metadata about your bucket.
	Labels map[string]string `json:"labels,omitempty"`

	// A list of the cloud providers or other platforms that are included in the
	// latest completed version. e.g aws, gcp, or azure.
	Platforms []string `json:"platforms"`
}

// Validate validates this hashicorp cloud packer 20230101 update bucket body
func (m *HashicorpCloudPacker20230101UpdateBucketBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud packer 20230101 update bucket body based on context it is used
func (m *HashicorpCloudPacker20230101UpdateBucketBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateBucketBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101UpdateBucketBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101UpdateBucketBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
