// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudPacker20230101ListSbomsResponse hashicorp cloud packer 20230101 list sboms response
//
// swagger:model hashicorp.cloud.packer_20230101.ListSbomsResponse
type HashicorpCloudPacker20230101ListSbomsResponse struct {

	// sboms
	Sboms []*HashicorpCloudPacker20230101Sbom `json:"sboms"`
}

// Validate validates this hashicorp cloud packer 20230101 list sboms response
func (m *HashicorpCloudPacker20230101ListSbomsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSboms(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101ListSbomsResponse) validateSboms(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Sboms) { // not required
		return nil
	}

	for i := 0; i < len(m.Sboms); i++ {
		if typeutils.IsZero(m.Sboms[i]) { // not required
			continue
		}

		if m.Sboms[i] != nil {
			if err := m.Sboms[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("sboms" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("sboms" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this hashicorp cloud packer 20230101 list sboms response based on the context it is used
func (m *HashicorpCloudPacker20230101ListSbomsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSboms(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudPacker20230101ListSbomsResponse) contextValidateSboms(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Sboms); i++ {

		if m.Sboms[i] != nil {

			if typeutils.IsZero(m.Sboms[i]) { // not required
				return nil
			}

			if err := m.Sboms[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("sboms" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("sboms" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ListSbomsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudPacker20230101ListSbomsResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudPacker20230101ListSbomsResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
