// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudPacker20230101DeleteBucketResponse hashicorp cloud packer 20230101 delete bucket response
//
// swagger:model hashicorp.cloud.packer_20230101.DeleteBucketResponse
type HashicorpCloudPacker20230101DeleteBucketResponse any
