DROP POLICY IF EXISTS tenant_isolation ON public.webhooks;
DROP POLICY IF EXISTS tenant_isolation ON public.webhook_outbox;
DROP POLICY IF EXISTS tenant_isolation ON public.webhook_deliveries;
DROP POLICY IF EXISTS tenant_isolation ON public.versions;
DROP POLICY IF EXISTS tenant_isolation ON public.scan_transcripts;
DROP POLICY IF EXISTS tenant_isolation ON public.scan_runs;
DROP POLICY IF EXISTS tenant_isolation ON public.scan_run_counters;
DROP POLICY IF EXISTS tenant_isolation ON public.scan_findings;
DROP POLICY IF EXISTS tenant_isolation ON public.sboms;
DROP POLICY IF EXISTS tenant_isolation ON public.sbom_packages;
DROP POLICY IF EXISTS tenant_isolation ON public.pins;
DROP POLICY IF EXISTS tenant_isolation ON public.pending_scans;
DROP POLICY IF EXISTS tenant_isolation ON public.channels;
DROP POLICY IF EXISTS tenant_isolation ON public.channel_assignments;
DROP POLICY IF EXISTS tenant_isolation ON public.builds;
DROP POLICY IF EXISTS tenant_isolation ON public.build_scan_state;
DROP POLICY IF EXISTS tenant_isolation ON public.buckets;
DROP POLICY IF EXISTS tenant_isolation ON public.bagdrop_configs;
DROP POLICY IF EXISTS tenant_isolation ON public.bagdrop_associations;
DROP POLICY IF EXISTS tenant_isolation ON public.artifacts;
ALTER TABLE IF EXISTS ONLY public.webhooks DROP CONSTRAINT IF EXISTS webhooks_organization_id_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.webhook_outbox DROP CONSTRAINT IF EXISTS webhook_outbox_organization_id_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.webhook_deliveries DROP CONSTRAINT IF EXISTS webhook_deliveries_organization_id_project_id_webhook_id_fkey;
ALTER TABLE IF EXISTS ONLY public.versions DROP CONSTRAINT IF EXISTS versions_organization_id_project_id_bucket_id_fkey;
ALTER TABLE IF EXISTS ONLY public.scan_transcripts DROP CONSTRAINT IF EXISTS scan_transcripts_organization_id_project_id_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.scan_transcripts DROP CONSTRAINT IF EXISTS scan_transcripts_bucket_run_fkey;
ALTER TABLE IF EXISTS ONLY public.scan_runs DROP CONSTRAINT IF EXISTS scan_runs_organization_id_project_id_build_id_fkey;
ALTER TABLE IF EXISTS ONLY public.scan_runs DROP CONSTRAINT IF EXISTS scan_runs_bucket_build_fkey;
ALTER TABLE IF EXISTS ONLY public.scan_findings DROP CONSTRAINT IF EXISTS scan_findings_organization_id_project_id_sbom_id_package_n_fkey;
ALTER TABLE IF EXISTS ONLY public.scan_findings DROP CONSTRAINT IF EXISTS scan_findings_organization_id_project_id_run_id_fkey;
ALTER TABLE IF EXISTS ONLY public.scan_findings DROP CONSTRAINT IF EXISTS scan_findings_bucket_run_fkey;
ALTER TABLE IF EXISTS ONLY public.sboms DROP CONSTRAINT IF EXISTS sboms_organization_id_project_id_build_id_fkey;
ALTER TABLE IF EXISTS ONLY public.sboms DROP CONSTRAINT IF EXISTS sboms_bucket_build_fkey;
ALTER TABLE IF EXISTS ONLY public.sbom_packages DROP CONSTRAINT IF EXISTS sbom_packages_organization_id_project_id_sbom_id_fkey;
ALTER TABLE IF EXISTS ONLY public.sbom_packages DROP CONSTRAINT IF EXISTS sbom_packages_bucket_sbom_fkey;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS projects_organization_id_fkey;
ALTER TABLE IF EXISTS ONLY public.principals DROP CONSTRAINT IF EXISTS principals_project_scope_fkey;
ALTER TABLE IF EXISTS ONLY public.principals DROP CONSTRAINT IF EXISTS principals_organization_id_fkey;
ALTER TABLE IF EXISTS ONLY public.principals DROP CONSTRAINT IF EXISTS principals_bucket_scope_fkey;
ALTER TABLE IF EXISTS ONLY public.principal_secrets DROP CONSTRAINT IF EXISTS principal_secrets_principal_id_fkey;
ALTER TABLE IF EXISTS ONLY public.pins DROP CONSTRAINT IF EXISTS pins_bucket_fkey;
ALTER TABLE IF EXISTS ONLY public.pending_scans DROP CONSTRAINT IF EXISTS pending_scans_organization_id_project_id_build_id_fkey;
ALTER TABLE IF EXISTS ONLY public.pending_scans DROP CONSTRAINT IF EXISTS pending_scans_bucket_build_fkey;
ALTER TABLE IF EXISTS ONLY public.channels DROP CONSTRAINT IF EXISTS channels_organization_id_project_id_bucket_id_fkey;
ALTER TABLE IF EXISTS ONLY public.channel_assignments DROP CONSTRAINT IF EXISTS channel_assignments_organization_id_project_id_version_id_fkey;
ALTER TABLE IF EXISTS ONLY public.channel_assignments DROP CONSTRAINT IF EXISTS channel_assignments_bucket_version_fkey;
ALTER TABLE IF EXISTS ONLY public.builds DROP CONSTRAINT IF EXISTS builds_organization_id_project_id_version_id_fkey;
ALTER TABLE IF EXISTS ONLY public.builds DROP CONSTRAINT IF EXISTS builds_bucket_version_fkey;
ALTER TABLE IF EXISTS ONLY public.build_scan_state DROP CONSTRAINT IF EXISTS build_scan_state_organization_id_project_id_latest_attempt_fkey;
ALTER TABLE IF EXISTS ONLY public.build_scan_state DROP CONSTRAINT IF EXISTS build_scan_state_organization_id_project_id_current_findin_fkey;
ALTER TABLE IF EXISTS ONLY public.build_scan_state DROP CONSTRAINT IF EXISTS build_scan_state_organization_id_project_id_build_id_fkey;
ALTER TABLE IF EXISTS ONLY public.build_scan_state DROP CONSTRAINT IF EXISTS build_scan_state_bucket_build_fkey;
ALTER TABLE IF EXISTS ONLY public.buckets DROP CONSTRAINT IF EXISTS buckets_organization_id_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.bagdrop_configs DROP CONSTRAINT IF EXISTS bagdrop_configs_organization_id_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.bagdrop_associations DROP CONSTRAINT IF EXISTS bagdrop_associations_organization_id_project_id_fkey;
ALTER TABLE IF EXISTS ONLY public.artifacts DROP CONSTRAINT IF EXISTS artifacts_organization_id_project_id_build_id_fkey;
ALTER TABLE IF EXISTS ONLY public.artifacts DROP CONSTRAINT IF EXISTS artifacts_bucket_build_fkey;
DROP TRIGGER IF EXISTS scan_runs_immutable ON public.scan_runs;
DROP TRIGGER IF EXISTS scan_findings_immutable ON public.scan_findings;
DROP TRIGGER IF EXISTS channel_assignments_append_only ON public.channel_assignments;
DROP INDEX IF EXISTS public.webhook_outbox_available_idx;
DROP INDEX IF EXISTS public.webhook_deliveries_ring_idx;
DROP INDEX IF EXISTS public.webhook_deliveries_retry_idx;
DROP INDEX IF EXISTS public.versions_bucket_sequence;
DROP INDEX IF EXISTS public.scan_runs_build;
DROP INDEX IF EXISTS public.pending_scans_fifo;
DROP INDEX IF EXISTS public.builds_parent_version_id_idx;
DROP INDEX IF EXISTS public.artifacts_external_identifier;
ALTER TABLE IF EXISTS ONLY public.webhooks DROP CONSTRAINT IF EXISTS webhooks_pkey;
ALTER TABLE IF EXISTS ONLY public.webhook_outbox DROP CONSTRAINT IF EXISTS webhook_outbox_pkey;
ALTER TABLE IF EXISTS ONLY public.webhook_deliveries DROP CONSTRAINT IF EXISTS webhook_deliveries_pkey;
ALTER TABLE IF EXISTS ONLY public.webhook_deliveries DROP CONSTRAINT IF EXISTS webhook_deliveries_organization_id_project_id_webhook_id_ev_key;
ALTER TABLE IF EXISTS ONLY public.versions DROP CONSTRAINT IF EXISTS versions_pkey;
ALTER TABLE IF EXISTS ONLY public.versions DROP CONSTRAINT IF EXISTS versions_organization_id_project_id_bucket_id_fingerprint_key;
ALTER TABLE IF EXISTS ONLY public.versions DROP CONSTRAINT IF EXISTS versions_bucket_id_id_key;
ALTER TABLE IF EXISTS ONLY public.scan_transcripts DROP CONSTRAINT IF EXISTS scan_transcripts_pkey;
ALTER TABLE IF EXISTS ONLY public.scan_runs DROP CONSTRAINT IF EXISTS scan_runs_pkey;
ALTER TABLE IF EXISTS ONLY public.scan_runs DROP CONSTRAINT IF EXISTS scan_runs_organization_id_project_id_run_sequence_key;
ALTER TABLE IF EXISTS ONLY public.scan_runs DROP CONSTRAINT IF EXISTS scan_runs_bucket_id_id_key;
ALTER TABLE IF EXISTS ONLY public.scan_run_counters DROP CONSTRAINT IF EXISTS scan_run_counters_pkey;
ALTER TABLE IF EXISTS ONLY public.scan_findings DROP CONSTRAINT IF EXISTS scan_findings_pkey;
ALTER TABLE IF EXISTS ONLY public.sboms DROP CONSTRAINT IF EXISTS sboms_pkey;
ALTER TABLE IF EXISTS ONLY public.sboms DROP CONSTRAINT IF EXISTS sboms_organization_id_project_id_build_id_name_key;
ALTER TABLE IF EXISTS ONLY public.sboms DROP CONSTRAINT IF EXISTS sboms_bucket_id_id_key;
ALTER TABLE IF EXISTS ONLY public.sbom_packages DROP CONSTRAINT IF EXISTS sbom_packages_pkey;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS projects_pkey;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS projects_organization_id_name_key;
ALTER TABLE IF EXISTS ONLY public.projects DROP CONSTRAINT IF EXISTS projects_organization_id_id_key;
ALTER TABLE IF EXISTS ONLY public.principals DROP CONSTRAINT IF EXISTS principals_pkey;
ALTER TABLE IF EXISTS ONLY public.principals DROP CONSTRAINT IF EXISTS principals_client_id_key;
ALTER TABLE IF EXISTS ONLY public.principal_secrets DROP CONSTRAINT IF EXISTS principal_secrets_pkey;
ALTER TABLE IF EXISTS ONLY public.pins DROP CONSTRAINT IF EXISTS pins_pkey;
ALTER TABLE IF EXISTS ONLY public.pending_scans DROP CONSTRAINT IF EXISTS pending_scans_pkey;
ALTER TABLE IF EXISTS ONLY public.organizations DROP CONSTRAINT IF EXISTS organizations_pkey;
ALTER TABLE IF EXISTS ONLY public.organizations DROP CONSTRAINT IF EXISTS organizations_name_key;
ALTER TABLE IF EXISTS ONLY public.keyring DROP CONSTRAINT IF EXISTS keyring_pkey;
ALTER TABLE IF EXISTS ONLY public.instance DROP CONSTRAINT IF EXISTS instance_pkey;
ALTER TABLE IF EXISTS ONLY public.encryption_mode DROP CONSTRAINT IF EXISTS encryption_mode_pkey;
ALTER TABLE IF EXISTS ONLY public.channels DROP CONSTRAINT IF EXISTS channels_pkey;
ALTER TABLE IF EXISTS ONLY public.channels DROP CONSTRAINT IF EXISTS channels_organization_id_project_id_bucket_id_name_key;
ALTER TABLE IF EXISTS ONLY public.channel_assignments DROP CONSTRAINT IF EXISTS channel_assignments_pkey;
ALTER TABLE IF EXISTS ONLY public.builds DROP CONSTRAINT IF EXISTS builds_pkey;
ALTER TABLE IF EXISTS ONLY public.builds DROP CONSTRAINT IF EXISTS builds_organization_id_project_id_version_id_component_type_key;
ALTER TABLE IF EXISTS ONLY public.builds DROP CONSTRAINT IF EXISTS builds_bucket_id_id_key;
ALTER TABLE IF EXISTS ONLY public.build_scan_state DROP CONSTRAINT IF EXISTS build_scan_state_pkey;
ALTER TABLE IF EXISTS ONLY public.buckets DROP CONSTRAINT IF EXISTS buckets_pkey;
ALTER TABLE IF EXISTS ONLY public.buckets DROP CONSTRAINT IF EXISTS buckets_organization_id_project_id_name_key;
ALTER TABLE IF EXISTS ONLY public.bagdrop_configs DROP CONSTRAINT IF EXISTS bagdrop_configs_pkey;
ALTER TABLE IF EXISTS ONLY public.bagdrop_associations DROP CONSTRAINT IF EXISTS bagdrop_associations_pkey;
ALTER TABLE IF EXISTS ONLY public.audit_targets DROP CONSTRAINT IF EXISTS audit_targets_slot_key;
ALTER TABLE IF EXISTS ONLY public.audit_targets DROP CONSTRAINT IF EXISTS audit_targets_pkey;
ALTER TABLE IF EXISTS ONLY public.artifacts DROP CONSTRAINT IF EXISTS artifacts_pkey;
ALTER TABLE IF EXISTS ONLY public.artifacts DROP CONSTRAINT IF EXISTS artifacts_organization_id_project_id_build_id_external_iden_key;
DROP TABLE IF EXISTS public.webhooks;
DROP TABLE IF EXISTS public.webhook_outbox;
DROP TABLE IF EXISTS public.webhook_deliveries;
DROP TABLE IF EXISTS public.versions;
DROP TABLE IF EXISTS public.scan_transcripts;
DROP TABLE IF EXISTS public.scan_runs;
DROP TABLE IF EXISTS public.scan_run_counters;
DROP TABLE IF EXISTS public.scan_findings;
DROP TABLE IF EXISTS public.sboms;
DROP TABLE IF EXISTS public.sbom_packages;
DROP TABLE IF EXISTS public.projects;
DROP TABLE IF EXISTS public.principals;
DROP TABLE IF EXISTS public.principal_secrets;
DROP TABLE IF EXISTS public.pins;
DROP TABLE IF EXISTS public.pending_scans;
DROP TABLE IF EXISTS public.organizations;
DROP TABLE IF EXISTS public.keyring;
DROP TABLE IF EXISTS public.instance;
DROP TABLE IF EXISTS public.encryption_mode;
DROP TABLE IF EXISTS public.channels;
DROP TABLE IF EXISTS public.channel_assignments;
DROP TABLE IF EXISTS public.builds;
DROP TABLE IF EXISTS public.build_scan_state;
DROP TABLE IF EXISTS public.buckets;
DROP TABLE IF EXISTS public.bagdrop_configs;
DROP TABLE IF EXISTS public.bagdrop_associations;
DROP TABLE IF EXISTS public.audit_targets;
DROP TABLE IF EXISTS public.artifacts;
DROP FUNCTION IF EXISTS public.reject_scan_row_change();
DROP FUNCTION IF EXISTS public.reject_channel_assignment_change();
