ALTER TABLE versions
    DROP CONSTRAINT versions_revocation_ancestor_shape,
    DROP CONSTRAINT versions_revocation_shape,
    DROP COLUMN revocation_inherited_from_name,
    DROP COLUMN revocation_inherited_from_fingerprint,
    DROP COLUMN revocation_inherited_from_bucket,
    DROP COLUMN revocation_inherited_from_id,
    DROP COLUMN revocation_author,
    DROP COLUMN revocation_message,
    DROP COLUMN revoke_at;
