apiVersion: v1
entries:
  dufflebag:
  - apiVersion: v2
    appVersion: latest
    created: "2026-08-12T22:00:47.50731+01:00"
    description: Self-contained single-replica dufflebag stack
    digest: 743bbab3c5e10f2c4e4d9b89bd5b527d8c9485063915352b9db9aae8459f48e3
    name: dufflebag
    type: application
    urls:
    - https://benemon.github.io/dufflebag/charts/dufflebag-0.0.0-dev.tgz
    version: 0.0.0-dev
generated: "2026-08-12T22:00:47.506659+01:00"
