// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Artifact struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	ProjectID          uuid.UUID `json:"project_id"`
	ID                 string    `json:"id"`
	BuildID            string    `json:"build_id"`
	ExternalIdentifier string    `json:"external_identifier"`
	Region             string    `json:"region"`
	CreatedAt          time.Time `json:"created_at"`
	IntegrityMac       []byte    `json:"integrity_mac"`
}

type AuditTarget struct {
	ID        uuid.UUID `json:"id"`
	Slot      int16     `json:"slot"`
	Path      string    `json:"path"`
	CreatedAt time.Time `json:"created_at"`
}

type BagdropConfig struct {
	OrganizationID   uuid.UUID       `json:"organization_id"`
	ProjectID        uuid.UUID       `json:"project_id"`
	Adapter          string          `json:"adapter"`
	Destination      json.RawMessage `json:"destination"`
	SealedSecret     []byte          `json:"sealed_secret"`
	Enabled          bool            `json:"enabled"`
	LastVerification []byte          `json:"last_verification"`
	LastVerifiedAt   sql.NullTime    `json:"last_verified_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type Bucket struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Description    string          `json:"description"`
	Labels         json.RawMessage `json:"labels"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Build struct {
	OrganizationID           uuid.UUID       `json:"organization_id"`
	ProjectID                uuid.UUID       `json:"project_id"`
	ID                       string          `json:"id"`
	VersionID                string          `json:"version_id"`
	ComponentType            string          `json:"component_type"`
	Status                   string          `json:"status"`
	Platform                 string          `json:"platform"`
	MetadataSeen             bool            `json:"metadata_seen"`
	PackerRunUuid            string          `json:"packer_run_uuid"`
	Labels                   json.RawMessage `json:"labels"`
	SourceExternalIdentifier string          `json:"source_external_identifier"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	ParentVersionID          sql.NullString  `json:"parent_version_id"`
	ParentChannelID          sql.NullString  `json:"parent_channel_id"`
	Metadata                 []byte          `json:"metadata"`
	IntegrityMac             []byte          `json:"integrity_mac"`
}

type Channel struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	BucketID       string    `json:"bucket_id"`
	Name           string    `json:"name"`
	Restricted     bool      `json:"restricted"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ChannelAssignment struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	ChannelID      string    `json:"channel_id"`
	VersionID      string    `json:"version_id"`
	AssignedAt     time.Time `json:"assigned_at"`
	IntegrityMac   []byte    `json:"integrity_mac"`
}

type EncryptionMode struct {
	ID         bool      `json:"id"`
	Encrypted  bool      `json:"encrypted"`
	RecordedAt time.Time `json:"recorded_at"`
}

type Instance struct {
	ID                bool          `json:"id"`
	InitializedAt     time.Time     `json:"initialized_at"`
	RecoveryDigest    []byte        `json:"recovery_digest"`
	RecoveryThreshold sql.NullInt32 `json:"recovery_threshold"`
}

type Keyring struct {
	Purpose    string    `json:"purpose"`
	Version    int32     `json:"version"`
	WrappedKey []byte    `json:"wrapped_key"`
	KekRef     string    `json:"kek_ref"`
	CreatedAt  time.Time `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Pin struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	BucketName     string    `json:"bucket_name"`
	PinnedAt       time.Time `json:"pinned_at"`
	PinnedBy       string    `json:"pinned_by"`
}

type Principal struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	ClientID       string        `json:"client_id"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
	ProjectID      uuid.NullUUID `json:"project_id"`
	CreatedAt      time.Time     `json:"created_at"`
	Role           string        `json:"role"`
	IntegrityMac   []byte        `json:"integrity_mac"`
}

type PrincipalSecret struct {
	ID           string       `json:"id"`
	PrincipalID  string       `json:"principal_id"`
	EncodedHash  string       `json:"encoded_hash"`
	CreatedAt    time.Time    `json:"created_at"`
	LastUsedAt   sql.NullTime `json:"last_used_at"`
	IntegrityMac []byte       `json:"integrity_mac"`
	ExpiresAt    sql.NullTime `json:"expires_at"`
}

type Project struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
}

type Sbom struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	BuildID        string    `json:"build_id"`
	Name           string    `json:"name"`
	Format         string    `json:"format"`
	CreatedAt      time.Time `json:"created_at"`
	ParseStatus    string    `json:"parse_status"`
	ParseError     string    `json:"parse_error"`
	ObjectKey      string    `json:"object_key"`
}

type SbomPackage struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	SbomID         string          `json:"sbom_id"`
	Name           string          `json:"name"`
	Version        string          `json:"version"`
	Purl           string          `json:"purl"`
	Licenses       json.RawMessage `json:"licenses"`
	ComponentPaths json.RawMessage `json:"component_paths"`
}

type Version struct {
	OrganizationID                     uuid.UUID      `json:"organization_id"`
	ProjectID                          uuid.UUID      `json:"project_id"`
	ID                                 string         `json:"id"`
	BucketID                           string         `json:"bucket_id"`
	Fingerprint                        string         `json:"fingerprint"`
	TemplateType                       string         `json:"template_type"`
	Complete                           bool           `json:"complete"`
	Sequence                           sql.NullInt32  `json:"sequence"`
	CreatedAt                          time.Time      `json:"created_at"`
	UpdatedAt                          time.Time      `json:"updated_at"`
	AuthorID                           string         `json:"author_id"`
	IntegrityMac                       []byte         `json:"integrity_mac"`
	RevokeAt                           sql.NullTime   `json:"revoke_at"`
	RevocationMessage                  sql.NullString `json:"revocation_message"`
	RevocationAuthor                   sql.NullString `json:"revocation_author"`
	RevocationInheritedFromID          sql.NullString `json:"revocation_inherited_from_id"`
	RevocationInheritedFromBucket      sql.NullString `json:"revocation_inherited_from_bucket"`
	RevocationInheritedFromFingerprint sql.NullString `json:"revocation_inherited_from_fingerprint"`
	RevocationInheritedFromName        sql.NullString `json:"revocation_inherited_from_name"`
}
