// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Artifact struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	ProjectID          uuid.UUID `json:"project_id"`
	ID                 string    `json:"id"`
	BuildID            string    `json:"build_id"`
	ExternalIdentifier string    `json:"external_identifier"`
	Region             string    `json:"region"`
	CreatedAt          time.Time `json:"created_at"`
	IntegrityMac       []byte    `json:"integrity_mac"`
	BucketID           string    `json:"bucket_id"`
}

type AuditTarget struct {
	ID        uuid.UUID `json:"id"`
	Slot      int16     `json:"slot"`
	Path      string    `json:"path"`
	CreatedAt time.Time `json:"created_at"`
}

type BagdropAssociation struct {
	OrganizationID   uuid.UUID      `json:"organization_id"`
	ProjectID        uuid.UUID      `json:"project_id"`
	BucketName       string         `json:"bucket_name"`
	State            string         `json:"state"`
	FirstAttemptedAt sql.NullTime   `json:"first_attempted_at"`
	LastSyncedAt     sql.NullTime   `json:"last_synced_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	LastAttemptAt    sql.NullTime   `json:"last_attempt_at"`
	LastSyncError    sql.NullString `json:"last_sync_error"`
}

type BagdropConfig struct {
	OrganizationID   uuid.UUID       `json:"organization_id"`
	ProjectID        uuid.UUID       `json:"project_id"`
	Adapter          string          `json:"adapter"`
	Destination      json.RawMessage `json:"destination"`
	SealedSecret     []byte          `json:"sealed_secret"`
	Enabled          bool            `json:"enabled"`
	LastVerification []byte          `json:"last_verification"`
	LastVerifiedAt   sql.NullTime    `json:"last_verified_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type Bucket struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Description    string          `json:"description"`
	Labels         json.RawMessage `json:"labels"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type Build struct {
	OrganizationID           uuid.UUID       `json:"organization_id"`
	ProjectID                uuid.UUID       `json:"project_id"`
	ID                       string          `json:"id"`
	VersionID                string          `json:"version_id"`
	ComponentType            string          `json:"component_type"`
	Status                   string          `json:"status"`
	Platform                 string          `json:"platform"`
	MetadataSeen             bool            `json:"metadata_seen"`
	PackerRunUuid            string          `json:"packer_run_uuid"`
	Labels                   json.RawMessage `json:"labels"`
	SourceExternalIdentifier string          `json:"source_external_identifier"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	ParentVersionID          sql.NullString  `json:"parent_version_id"`
	ParentChannelID          sql.NullString  `json:"parent_channel_id"`
	Metadata                 []byte          `json:"metadata"`
	IntegrityMac             []byte          `json:"integrity_mac"`
	BucketID                 string          `json:"bucket_id"`
}

type BuildScanState struct {
	OrganizationID       uuid.UUID      `json:"organization_id"`
	ProjectID            uuid.UUID      `json:"project_id"`
	BuildID              string         `json:"build_id"`
	CurrentFindingsRunID sql.NullString `json:"current_findings_run_id"`
	LatestAttemptRunID   string         `json:"latest_attempt_run_id"`
	IntegrityMac         []byte         `json:"integrity_mac"`
	BucketID             string         `json:"bucket_id"`
}

type Channel struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	BucketID       string    `json:"bucket_id"`
	Name           string    `json:"name"`
	Restricted     bool      `json:"restricted"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ChannelAssignment struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	ChannelID      string    `json:"channel_id"`
	VersionID      string    `json:"version_id"`
	AssignedAt     time.Time `json:"assigned_at"`
	IntegrityMac   []byte    `json:"integrity_mac"`
	BucketID       string    `json:"bucket_id"`
}

type EncryptionMode struct {
	ID         bool      `json:"id"`
	Encrypted  bool      `json:"encrypted"`
	RecordedAt time.Time `json:"recorded_at"`
}

type Instance struct {
	ID                bool          `json:"id"`
	InitializedAt     time.Time     `json:"initialized_at"`
	RecoveryDigest    []byte        `json:"recovery_digest"`
	RecoveryThreshold sql.NullInt32 `json:"recovery_threshold"`
}

type Keyring struct {
	Purpose    string    `json:"purpose"`
	Version    int32     `json:"version"`
	WrappedKey []byte    `json:"wrapped_key"`
	KekRef     string    `json:"kek_ref"`
	CreatedAt  time.Time `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PendingScan struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	BuildID        string    `json:"build_id"`
	EnqueuedAt     time.Time `json:"enqueued_at"`
	Reason         string    `json:"reason"`
	BucketID       string    `json:"bucket_id"`
}

type Pin struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	PinnedAt       time.Time `json:"pinned_at"`
	PinnedBy       string    `json:"pinned_by"`
	BucketID       string    `json:"bucket_id"`
}

type Principal struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	ClientID       string         `json:"client_id"`
	OrganizationID uuid.NullUUID  `json:"organization_id"`
	ProjectID      uuid.NullUUID  `json:"project_id"`
	CreatedAt      time.Time      `json:"created_at"`
	Role           string         `json:"role"`
	IntegrityMac   []byte         `json:"integrity_mac"`
	BucketID       sql.NullString `json:"bucket_id"`
}

type PrincipalSecret struct {
	ID           string       `json:"id"`
	PrincipalID  string       `json:"principal_id"`
	EncodedHash  string       `json:"encoded_hash"`
	CreatedAt    time.Time    `json:"created_at"`
	LastUsedAt   sql.NullTime `json:"last_used_at"`
	IntegrityMac []byte       `json:"integrity_mac"`
	ExpiresAt    sql.NullTime `json:"expires_at"`
}

type Project struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
}

type Sbom struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	BuildID        string    `json:"build_id"`
	Name           string    `json:"name"`
	Format         string    `json:"format"`
	CreatedAt      time.Time `json:"created_at"`
	ParseStatus    string    `json:"parse_status"`
	ParseError     string    `json:"parse_error"`
	ObjectKey      string    `json:"object_key"`
	BucketID       string    `json:"bucket_id"`
}

type SbomPackage struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	SbomID         string          `json:"sbom_id"`
	Name           string          `json:"name"`
	Version        string          `json:"version"`
	Purl           string          `json:"purl"`
	Licenses       json.RawMessage `json:"licenses"`
	ComponentPaths json.RawMessage `json:"component_paths"`
	BucketID       string          `json:"bucket_id"`
}

type ScanFinding struct {
	OrganizationID  uuid.UUID       `json:"organization_id"`
	ProjectID       uuid.UUID       `json:"project_id"`
	RunID           string          `json:"run_id"`
	SbomID          string          `json:"sbom_id"`
	PackageName     string          `json:"package_name"`
	PackageVersion  string          `json:"package_version"`
	Purl            string          `json:"purl"`
	AdvisoryID      string          `json:"advisory_id"`
	Summary         string          `json:"summary"`
	Aliases         json.RawMessage `json:"aliases"`
	Related         json.RawMessage `json:"related"`
	Published       sql.NullTime    `json:"published"`
	Modified        sql.NullTime    `json:"modified"`
	Withdrawn       sql.NullTime    `json:"withdrawn"`
	FixedVersions   json.RawMessage `json:"fixed_versions"`
	Severities      json.RawMessage `json:"severities"`
	DerivedSeverity string          `json:"derived_severity"`
	FirstSeenAt     time.Time       `json:"first_seen_at"`
	IntegrityMac    []byte          `json:"integrity_mac"`
	BucketID        string          `json:"bucket_id"`
}

type ScanRun struct {
	OrganizationID   uuid.UUID       `json:"organization_id"`
	ProjectID        uuid.UUID       `json:"project_id"`
	ID               string          `json:"id"`
	BuildID          string          `json:"build_id"`
	RunSequence      int64           `json:"run_sequence"`
	Status           string          `json:"status"`
	Error            string          `json:"error"`
	Adapter          string          `json:"adapter"`
	Engine           string          `json:"engine"`
	DatabaseRevision string          `json:"database_revision"`
	ObservedAt       time.Time       `json:"observed_at"`
	TranscriptDigest string          `json:"transcript_digest"`
	Coverage         json.RawMessage `json:"coverage"`
	CreatedAt        time.Time       `json:"created_at"`
	IntegrityMac     []byte          `json:"integrity_mac"`
	BucketID         string          `json:"bucket_id"`
}

type ScanRunCounter struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	NextSequence   int64     `json:"next_sequence"`
}

type ScanTranscript struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	RunID          string    `json:"run_id"`
	ObjectKey      string    `json:"object_key"`
	ExpiresAt      time.Time `json:"expires_at"`
	IntegrityMac   []byte    `json:"integrity_mac"`
	BucketID       string    `json:"bucket_id"`
}

type Version struct {
	OrganizationID                     uuid.UUID      `json:"organization_id"`
	ProjectID                          uuid.UUID      `json:"project_id"`
	ID                                 string         `json:"id"`
	BucketID                           string         `json:"bucket_id"`
	Fingerprint                        string         `json:"fingerprint"`
	TemplateType                       string         `json:"template_type"`
	Complete                           bool           `json:"complete"`
	Sequence                           sql.NullInt32  `json:"sequence"`
	CreatedAt                          time.Time      `json:"created_at"`
	UpdatedAt                          time.Time      `json:"updated_at"`
	AuthorID                           string         `json:"author_id"`
	IntegrityMac                       []byte         `json:"integrity_mac"`
	RevokeAt                           sql.NullTime   `json:"revoke_at"`
	RevocationMessage                  sql.NullString `json:"revocation_message"`
	RevocationAuthor                   sql.NullString `json:"revocation_author"`
	RevocationInheritedFromID          sql.NullString `json:"revocation_inherited_from_id"`
	RevocationInheritedFromBucket      sql.NullString `json:"revocation_inherited_from_bucket"`
	RevocationInheritedFromFingerprint sql.NullString `json:"revocation_inherited_from_fingerprint"`
	RevocationInheritedFromName        sql.NullString `json:"revocation_inherited_from_name"`
}

type Webhook struct {
	OrganizationID        uuid.UUID      `json:"organization_id"`
	ProjectID             uuid.UUID      `json:"project_id"`
	ID                    uuid.UUID      `json:"id"`
	Name                  string         `json:"name"`
	Url                   string         `json:"url"`
	Description           string         `json:"description"`
	SealedSecret          []byte         `json:"sealed_secret"`
	Events                []string       `json:"events"`
	State                 string         `json:"state"`
	LastVerificationAt    sql.NullTime   `json:"last_verification_at"`
	LastVerificationError sql.NullString `json:"last_verification_error"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type WebhookDelivery struct {
	OrganizationID   uuid.UUID      `json:"organization_id"`
	ProjectID        uuid.UUID      `json:"project_id"`
	ID               uuid.UUID      `json:"id"`
	WebhookID        uuid.UUID      `json:"webhook_id"`
	EventID          string         `json:"event_id"`
	Operation        string         `json:"operation"`
	Status           string         `json:"status"`
	AttemptCount     int32          `json:"attempt_count"`
	FirstAttemptedAt sql.NullTime   `json:"first_attempted_at"`
	LastAttemptedAt  sql.NullTime   `json:"last_attempted_at"`
	NextAttemptAt    sql.NullTime   `json:"next_attempt_at"`
	ResponseCode     sql.NullInt32  `json:"response_code"`
	Detail           sql.NullString `json:"detail"`
	CreatedAt        time.Time      `json:"created_at"`
}

type WebhookOutbox struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	EventID        string          `json:"event_id"`
	OccurredAt     time.Time       `json:"occurred_at"`
	Operation      string          `json:"operation"`
	Target         json.RawMessage `json:"target"`
	Actor          json.RawMessage `json:"actor"`
	Payload        json.RawMessage `json:"payload"`
	AvailableAt    time.Time       `json:"available_at"`
}
