// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgresdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const bagDropBucketExists = `-- name: BagDropBucketExists :one
SELECT EXISTS (SELECT 1 FROM buckets WHERE name = $1)
`

func (q *Queries) BagDropBucketExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, bagDropBucketExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const completeVersion = `-- name: CompleteVersion :one
UPDATE versions
SET complete = true, sequence = $2, updated_at = $3
WHERE id = $1 AND complete = false
RETURNING organization_id, project_id, id, bucket_id, fingerprint, template_type, complete, sequence, created_at, updated_at, author_id, integrity_mac, revoke_at, revocation_message, revocation_author, revocation_inherited_from_id, revocation_inherited_from_bucket, revocation_inherited_from_fingerprint, revocation_inherited_from_name
`

type CompleteVersionParams struct {
	ID        string        `json:"id"`
	Sequence  sql.NullInt32 `json:"sequence"`
	UpdatedAt time.Time     `json:"updated_at"`
}

func (q *Queries) CompleteVersion(ctx context.Context, arg CompleteVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, completeVersion, arg.ID, arg.Sequence, arg.UpdatedAt)
	var i Version
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.BucketID,
		&i.Fingerprint,
		&i.TemplateType,
		&i.Complete,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.IntegrityMac,
		&i.RevokeAt,
		&i.RevocationMessage,
		&i.RevocationAuthor,
		&i.RevocationInheritedFromID,
		&i.RevocationInheritedFromBucket,
		&i.RevocationInheritedFromFingerprint,
		&i.RevocationInheritedFromName,
	)
	return i, err
}

const countRootPrincipals = `-- name: CountRootPrincipals :one
SELECT count(*) FROM principals WHERE role = 'root'
`

func (q *Queries) CountRootPrincipals(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRootPrincipals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
    organization_id, project_id, id, build_id, external_identifier, region, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (organization_id, project_id, build_id, external_identifier)
DO UPDATE SET external_identifier = EXCLUDED.external_identifier
RETURNING organization_id, project_id, id, build_id, external_identifier, region, created_at, integrity_mac
`

type CreateArtifactParams struct {
	OrganizationID     uuid.UUID `json:"organization_id"`
	ProjectID          uuid.UUID `json:"project_id"`
	ID                 string    `json:"id"`
	BuildID            string    `json:"build_id"`
	ExternalIdentifier string    `json:"external_identifier"`
	Region             string    `json:"region"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ID,
		arg.BuildID,
		arg.ExternalIdentifier,
		arg.Region,
		arg.CreatedAt,
	)
	var i Artifact
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.BuildID,
		&i.ExternalIdentifier,
		&i.Region,
		&i.CreatedAt,
		&i.IntegrityMac,
	)
	return i, err
}

const createAuditTarget = `-- name: CreateAuditTarget :one
INSERT INTO audit_targets (id, slot, path, created_at)
SELECT $1, free.slot, $2, $3
FROM (
    SELECT s.slot
    FROM generate_series(1, 3) AS s(slot)
    WHERE NOT EXISTS (SELECT 1 FROM audit_targets t WHERE t.slot = s.slot)
    ORDER BY s.slot
    LIMIT 1
) AS free
ON CONFLICT DO NOTHING
RETURNING id, slot, path, created_at
`

type CreateAuditTargetParams struct {
	ID        uuid.UUID `json:"id"`
	Path      string    `json:"path"`
	CreatedAt time.Time `json:"created_at"`
}

// Server-assigned slot: the lowest free value in 1..3, chosen inside the
// caller's transaction under the slot lock. Returns no row in exactly two
// cases, and the repository maps both to a conflict: all three slots are
// taken, so the sub-select is empty; or the row collides on id or slot, which
// ON CONFLICT DO NOTHING swallows rather than surfacing as a raw pg error.
func (q *Queries) CreateAuditTarget(ctx context.Context, arg CreateAuditTargetParams) (AuditTarget, error) {
	row := q.db.QueryRowContext(ctx, createAuditTarget, arg.ID, arg.Path, arg.CreatedAt)
	var i AuditTarget
	err := row.Scan(
		&i.ID,
		&i.Slot,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (
    organization_id, project_id, id, name, description, labels, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT DO NOTHING
RETURNING organization_id, project_id, id, name, description, labels, created_at, updated_at
`

type CreateBucketParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Description    string          `json:"description"`
	Labels         json.RawMessage `json:"labels"`
	CreatedAt      time.Time       `json:"created_at"`
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, createBucket,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Labels,
		arg.CreatedAt,
	)
	var i Bucket
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (
    organization_id, project_id, id, version_id, component_type, status,
    platform, metadata_seen, packer_run_uuid, labels,
    source_external_identifier, parent_version_id, parent_channel_id, created_at, updated_at
)
SELECT $1, $2, $3, versions.id, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $15
FROM versions
JOIN buckets ON buckets.id = versions.bucket_id
WHERE buckets.name = $4 AND versions.fingerprint = $5
ON CONFLICT (organization_id, project_id, version_id, component_type)
DO UPDATE SET component_type = builds.component_type
RETURNING organization_id, project_id, id, version_id, component_type, status, platform, metadata_seen, packer_run_uuid, labels, source_external_identifier, created_at, updated_at, parent_version_id, parent_channel_id, metadata, integrity_mac
`

type CreateBuildParams struct {
	OrganizationID           uuid.UUID       `json:"organization_id"`
	ProjectID                uuid.UUID       `json:"project_id"`
	ID                       string          `json:"id"`
	Name                     string          `json:"name"`
	Fingerprint              string          `json:"fingerprint"`
	ComponentType            string          `json:"component_type"`
	Status                   string          `json:"status"`
	Platform                 string          `json:"platform"`
	MetadataSeen             bool            `json:"metadata_seen"`
	PackerRunUuid            string          `json:"packer_run_uuid"`
	Labels                   json.RawMessage `json:"labels"`
	SourceExternalIdentifier string          `json:"source_external_identifier"`
	ParentVersionID          sql.NullString  `json:"parent_version_id"`
	ParentChannelID          sql.NullString  `json:"parent_channel_id"`
	CreatedAt                time.Time       `json:"created_at"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRowContext(ctx, createBuild,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Fingerprint,
		arg.ComponentType,
		arg.Status,
		arg.Platform,
		arg.MetadataSeen,
		arg.PackerRunUuid,
		arg.Labels,
		arg.SourceExternalIdentifier,
		arg.ParentVersionID,
		arg.ParentChannelID,
		arg.CreatedAt,
	)
	var i Build
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.VersionID,
		&i.ComponentType,
		&i.Status,
		&i.Platform,
		&i.MetadataSeen,
		&i.PackerRunUuid,
		&i.Labels,
		&i.SourceExternalIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentVersionID,
		&i.ParentChannelID,
		&i.Metadata,
		&i.IntegrityMac,
	)
	return i, err
}

const createKeyringEntry = `-- name: CreateKeyringEntry :execrows
INSERT INTO keyring (purpose, version, wrapped_key, kek_ref, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (purpose, version) DO NOTHING
`

type CreateKeyringEntryParams struct {
	Purpose    string    `json:"purpose"`
	Version    int32     `json:"version"`
	WrappedKey []byte    `json:"wrapped_key"`
	KekRef     string    `json:"kek_ref"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateKeyringEntry(ctx context.Context, arg CreateKeyringEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createKeyringEntry,
		arg.Purpose,
		arg.Version,
		arg.WrappedKey,
		arg.KekRef,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, created_at)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, name, created_at
`

type CreateOrganizationParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, arg.ID, arg.Name, arg.CreatedAt)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO principals (
    id, name, client_id, organization_id, project_id, role, created_at, integrity_mac
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT DO NOTHING
RETURNING id
`

type CreatePrincipalParams struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	ClientID       string        `json:"client_id"`
	OrganizationID uuid.NullUUID `json:"organization_id"`
	ProjectID      uuid.NullUUID `json:"project_id"`
	Role           string        `json:"role"`
	CreatedAt      time.Time     `json:"created_at"`
	IntegrityMac   []byte        `json:"integrity_mac"`
}

func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createPrincipal,
		arg.ID,
		arg.Name,
		arg.ClientID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Role,
		arg.CreatedAt,
		arg.IntegrityMac,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createPrincipalSecret = `-- name: CreatePrincipalSecret :one
INSERT INTO principal_secrets (
    id, principal_id, encoded_hash, created_at, last_used_at, expires_at, integrity_mac
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id
`

type CreatePrincipalSecretParams struct {
	ID           string       `json:"id"`
	PrincipalID  string       `json:"principal_id"`
	EncodedHash  string       `json:"encoded_hash"`
	CreatedAt    time.Time    `json:"created_at"`
	LastUsedAt   sql.NullTime `json:"last_used_at"`
	ExpiresAt    sql.NullTime `json:"expires_at"`
	IntegrityMac []byte       `json:"integrity_mac"`
}

func (q *Queries) CreatePrincipalSecret(ctx context.Context, arg CreatePrincipalSecretParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createPrincipalSecret,
		arg.ID,
		arg.PrincipalID,
		arg.EncodedHash,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.IntegrityMac,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, organization_id, name, created_at)
SELECT $1, $2, $3, $4
FROM organizations
WHERE id = $2
ON CONFLICT DO NOTHING
RETURNING id, organization_id, name, created_at
`

type CreateProjectParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createVersion = `-- name: CreateVersion :one
INSERT INTO versions (
    organization_id, project_id, id, bucket_id, fingerprint, template_type,
    complete, sequence, created_at, updated_at, author_id
)
SELECT $1, $2, $3, buckets.id, $5, $6, $7, $8, $9, $10, $11
FROM buckets
WHERE buckets.name = $4
ON CONFLICT (organization_id, project_id, bucket_id, fingerprint)
DO UPDATE SET fingerprint = versions.fingerprint
RETURNING organization_id, project_id, id, bucket_id, fingerprint, template_type, complete, sequence, created_at, updated_at, author_id, integrity_mac, revoke_at, revocation_message, revocation_author, revocation_inherited_from_id, revocation_inherited_from_bucket, revocation_inherited_from_fingerprint, revocation_inherited_from_name
`

type CreateVersionParams struct {
	OrganizationID uuid.UUID     `json:"organization_id"`
	ProjectID      uuid.UUID     `json:"project_id"`
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Fingerprint    string        `json:"fingerprint"`
	TemplateType   string        `json:"template_type"`
	Complete       bool          `json:"complete"`
	Sequence       sql.NullInt32 `json:"sequence"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	AuthorID       string        `json:"author_id"`
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, createVersion,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Fingerprint,
		arg.TemplateType,
		arg.Complete,
		arg.Sequence,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.AuthorID,
	)
	var i Version
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.BucketID,
		&i.Fingerprint,
		&i.TemplateType,
		&i.Complete,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.IntegrityMac,
		&i.RevokeAt,
		&i.RevocationMessage,
		&i.RevocationAuthor,
		&i.RevocationInheritedFromID,
		&i.RevocationInheritedFromBucket,
		&i.RevocationInheritedFromFingerprint,
		&i.RevocationInheritedFromName,
	)
	return i, err
}

const deleteAuditTarget = `-- name: DeleteAuditTarget :execrows
DELETE FROM audit_targets
WHERE id = $1
`

func (q *Queries) DeleteAuditTarget(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditTarget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBagDropConfig = `-- name: DeleteBagDropConfig :execrows
DELETE FROM bagdrop_configs
WHERE NOT EXISTS (
    SELECT 1 FROM bagdrop_associations
    WHERE state = 'pending_removal' OR first_attempted_at IS NOT NULL
)
`

func (q *Queries) DeleteBagDropConfig(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBagDropConfig)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBucketByName = `-- name: DeleteBucketByName :one
DELETE FROM buckets WHERE name = $1
RETURNING id
`

func (q *Queries) DeleteBucketByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteBucketByName, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteOrganization = `-- name: DeleteOrganization :one
WITH target AS (
    -- Columns qualified: sqlc's analyser otherwise reads bare ` + "`" + `id` + "`" + ` as ambiguous
    -- between the CTE's projection and the table.
    SELECT organizations.id FROM organizations WHERE organizations.id = $1
),
deleted AS (
    DELETE FROM organizations
    WHERE id = $1
      AND NOT EXISTS (
          SELECT 1 FROM projects WHERE organization_id = $1
      )
    RETURNING id
)
SELECT CASE
    WHEN EXISTS (SELECT 1 FROM deleted) THEN 'deleted'
    WHEN EXISTS (SELECT 1 FROM target) THEN 'conflict'
    ELSE 'not_found'
END AS result
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteOrganization, id)
	var result string
	err := row.Scan(&result)
	return result, err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM pins WHERE bucket_name = $1
`

func (q *Queries) DeletePin(ctx context.Context, bucketName string) error {
	_, err := q.db.ExecContext(ctx, deletePin, bucketName)
	return err
}

const deletePrincipal = `-- name: DeletePrincipal :execrows
DELETE FROM principals
WHERE id = $1
`

func (q *Queries) DeletePrincipal(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrincipal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePrincipalSecret = `-- name: DeletePrincipalSecret :execrows
DELETE FROM principal_secrets
WHERE principal_id = $1 AND id = $2
`

type DeletePrincipalSecretParams struct {
	PrincipalID string `json:"principal_id"`
	ID          string `json:"id"`
}

func (q *Queries) DeletePrincipalSecret(ctx context.Context, arg DeletePrincipalSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrincipalSecret, arg.PrincipalID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProject = `-- name: DeleteProject :one
WITH target AS (
    SELECT projects.id
    FROM projects
    WHERE projects.organization_id = $1 AND projects.id = $2
),
deleted AS (
    DELETE FROM projects
    WHERE organization_id = $1
      AND id = $2
      AND NOT EXISTS (
          SELECT 1
          FROM buckets
          WHERE organization_id = $1 AND project_id = $2
      )
    RETURNING id
)
SELECT CASE
    WHEN EXISTS (SELECT 1 FROM deleted) THEN 'deleted'
    WHEN EXISTS (SELECT 1 FROM target) THEN 'conflict'
    ELSE 'not_found'
END AS result
`

type DeleteProjectParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteProject, arg.OrganizationID, arg.ID)
	var result string
	err := row.Scan(&result)
	return result, err
}

const disableBagDrop = `-- name: DisableBagDrop :one
UPDATE bagdrop_configs
SET enabled = false, updated_at = $1
RETURNING organization_id, project_id, adapter, destination, sealed_secret, enabled, last_verification, last_verified_at, created_at, updated_at
`

func (q *Queries) DisableBagDrop(ctx context.Context, updatedAt time.Time) (BagdropConfig, error) {
	row := q.db.QueryRowContext(ctx, disableBagDrop, updatedAt)
	var i BagdropConfig
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.Adapter,
		&i.Destination,
		&i.SealedSecret,
		&i.Enabled,
		&i.LastVerification,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enableBagDrop = `-- name: EnableBagDrop :one
UPDATE bagdrop_configs
SET enabled = true, last_verification = $1, last_verified_at = $2, updated_at = $2
RETURNING organization_id, project_id, adapter, destination, sealed_secret, enabled, last_verification, last_verified_at, created_at, updated_at
`

type EnableBagDropParams struct {
	LastVerification []byte       `json:"last_verification"`
	LastVerifiedAt   sql.NullTime `json:"last_verified_at"`
}

func (q *Queries) EnableBagDrop(ctx context.Context, arg EnableBagDropParams) (BagdropConfig, error) {
	row := q.db.QueryRowContext(ctx, enableBagDrop, arg.LastVerification, arg.LastVerifiedAt)
	var i BagdropConfig
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.Adapter,
		&i.Destination,
		&i.SealedSecret,
		&i.Enabled,
		&i.LastVerification,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBagDropConfig = `-- name: GetBagDropConfig :one
SELECT organization_id, project_id, adapter, destination, sealed_secret, enabled, last_verification, last_verified_at, created_at, updated_at
FROM bagdrop_configs
`

func (q *Queries) GetBagDropConfig(ctx context.Context) (BagdropConfig, error) {
	row := q.db.QueryRowContext(ctx, getBagDropConfig)
	var i BagdropConfig
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.Adapter,
		&i.Destination,
		&i.SealedSecret,
		&i.Enabled,
		&i.LastVerification,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBucketByName = `-- name: GetBucketByName :one
SELECT organization_id, project_id, id, name, description, labels, created_at, updated_at FROM buckets WHERE name = $1
`

func (q *Queries) GetBucketByName(ctx context.Context, name string) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, getBucketByName, name)
	var i Bucket
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuild = `-- name: GetBuild :one
SELECT builds.organization_id, builds.project_id, builds.id, builds.version_id, builds.component_type, builds.status, builds.platform, builds.metadata_seen, builds.packer_run_uuid, builds.labels, builds.source_external_identifier, builds.created_at, builds.updated_at, builds.parent_version_id, builds.parent_channel_id, builds.metadata, builds.integrity_mac
FROM builds
JOIN versions ON versions.id = builds.version_id
JOIN buckets ON buckets.id = versions.bucket_id
WHERE buckets.name = $1 AND versions.fingerprint = $2 AND builds.id = $3
`

type GetBuildParams struct {
	Name        string `json:"name"`
	Fingerprint string `json:"fingerprint"`
	ID          string `json:"id"`
}

func (q *Queries) GetBuild(ctx context.Context, arg GetBuildParams) (Build, error) {
	row := q.db.QueryRowContext(ctx, getBuild, arg.Name, arg.Fingerprint, arg.ID)
	var i Build
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.VersionID,
		&i.ComponentType,
		&i.Status,
		&i.Platform,
		&i.MetadataSeen,
		&i.PackerRunUuid,
		&i.Labels,
		&i.SourceExternalIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentVersionID,
		&i.ParentChannelID,
		&i.Metadata,
		&i.IntegrityMac,
	)
	return i, err
}

const getEncryptionMode = `-- name: GetEncryptionMode :one
SELECT encrypted
FROM encryption_mode
WHERE id = true
`

func (q *Queries) GetEncryptionMode(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, getEncryptionMode)
	var encrypted bool
	err := row.Scan(&encrypted)
	return encrypted, err
}

const getInitializationTimestamp = `-- name: GetInitializationTimestamp :one
SELECT initialized_at
FROM instance
WHERE id = true
`

func (q *Queries) GetInitializationTimestamp(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getInitializationTimestamp)
	var initialized_at time.Time
	err := row.Scan(&initialized_at)
	return initialized_at, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, created_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getPin = `-- name: GetPin :one
SELECT bucket_name, pinned_at, pinned_by
FROM pins
WHERE bucket_name = $1
`

type GetPinRow struct {
	BucketName string    `json:"bucket_name"`
	PinnedAt   time.Time `json:"pinned_at"`
	PinnedBy   string    `json:"pinned_by"`
}

func (q *Queries) GetPin(ctx context.Context, bucketName string) (GetPinRow, error) {
	row := q.db.QueryRowContext(ctx, getPin, bucketName)
	var i GetPinRow
	err := row.Scan(&i.BucketName, &i.PinnedAt, &i.PinnedBy)
	return i, err
}

const getPrincipalByClientID = `-- name: GetPrincipalByClientID :one
SELECT id, name, client_id, organization_id, project_id, created_at, role, integrity_mac
FROM principals
WHERE client_id = $1
`

func (q *Queries) GetPrincipalByClientID(ctx context.Context, clientID string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByClientID, clientID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.Role,
		&i.IntegrityMac,
	)
	return i, err
}

const getPrincipalByID = `-- name: GetPrincipalByID :one
SELECT id, name, client_id, organization_id, project_id, created_at, role, integrity_mac
FROM principals
WHERE id = $1
`

func (q *Queries) GetPrincipalByID(ctx context.Context, id string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByID, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.Role,
		&i.IntegrityMac,
	)
	return i, err
}

const getPrincipalByIDForUpdate = `-- name: GetPrincipalByIDForUpdate :one
SELECT id, name, client_id, organization_id, project_id, created_at, role, integrity_mac
FROM principals
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPrincipalByIDForUpdate(ctx context.Context, id string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByIDForUpdate, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.Role,
		&i.IntegrityMac,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, organization_id, name, created_at
FROM projects
WHERE organization_id = $1 AND id = $2
`

type GetProjectParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.OrganizationID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getRecoveryVerifier = `-- name: GetRecoveryVerifier :one
SELECT recovery_digest, recovery_threshold
FROM instance
WHERE id = true
`

type GetRecoveryVerifierRow struct {
	RecoveryDigest    []byte        `json:"recovery_digest"`
	RecoveryThreshold sql.NullInt32 `json:"recovery_threshold"`
}

func (q *Queries) GetRecoveryVerifier(ctx context.Context) (GetRecoveryVerifierRow, error) {
	row := q.db.QueryRowContext(ctx, getRecoveryVerifier)
	var i GetRecoveryVerifierRow
	err := row.Scan(&i.RecoveryDigest, &i.RecoveryThreshold)
	return i, err
}

const getVersionByFingerprint = `-- name: GetVersionByFingerprint :one
SELECT versions.organization_id, versions.project_id, versions.id, versions.bucket_id, versions.fingerprint, versions.template_type, versions.complete, versions.sequence, versions.created_at, versions.updated_at, versions.author_id, versions.integrity_mac, versions.revoke_at, versions.revocation_message, versions.revocation_author, versions.revocation_inherited_from_id, versions.revocation_inherited_from_bucket, versions.revocation_inherited_from_fingerprint, versions.revocation_inherited_from_name, buckets.name AS bucket_name
FROM versions
JOIN buckets ON buckets.id = versions.bucket_id
WHERE buckets.name = $1 AND versions.fingerprint = $2
`

type GetVersionByFingerprintParams struct {
	Name        string `json:"name"`
	Fingerprint string `json:"fingerprint"`
}

type GetVersionByFingerprintRow struct {
	OrganizationID                     uuid.UUID      `json:"organization_id"`
	ProjectID                          uuid.UUID      `json:"project_id"`
	ID                                 string         `json:"id"`
	BucketID                           string         `json:"bucket_id"`
	Fingerprint                        string         `json:"fingerprint"`
	TemplateType                       string         `json:"template_type"`
	Complete                           bool           `json:"complete"`
	Sequence                           sql.NullInt32  `json:"sequence"`
	CreatedAt                          time.Time      `json:"created_at"`
	UpdatedAt                          time.Time      `json:"updated_at"`
	AuthorID                           string         `json:"author_id"`
	IntegrityMac                       []byte         `json:"integrity_mac"`
	RevokeAt                           sql.NullTime   `json:"revoke_at"`
	RevocationMessage                  sql.NullString `json:"revocation_message"`
	RevocationAuthor                   sql.NullString `json:"revocation_author"`
	RevocationInheritedFromID          sql.NullString `json:"revocation_inherited_from_id"`
	RevocationInheritedFromBucket      sql.NullString `json:"revocation_inherited_from_bucket"`
	RevocationInheritedFromFingerprint sql.NullString `json:"revocation_inherited_from_fingerprint"`
	RevocationInheritedFromName        sql.NullString `json:"revocation_inherited_from_name"`
	BucketName                         string         `json:"bucket_name"`
}

func (q *Queries) GetVersionByFingerprint(ctx context.Context, arg GetVersionByFingerprintParams) (GetVersionByFingerprintRow, error) {
	row := q.db.QueryRowContext(ctx, getVersionByFingerprint, arg.Name, arg.Fingerprint)
	var i GetVersionByFingerprintRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.BucketID,
		&i.Fingerprint,
		&i.TemplateType,
		&i.Complete,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.IntegrityMac,
		&i.RevokeAt,
		&i.RevocationMessage,
		&i.RevocationAuthor,
		&i.RevocationInheritedFromID,
		&i.RevocationInheritedFromBucket,
		&i.RevocationInheritedFromFingerprint,
		&i.RevocationInheritedFromName,
		&i.BucketName,
	)
	return i, err
}

const getVersionRelationships = `-- name: GetVersionRelationships :one
WITH parents AS (
    SELECT builds.parent_version_id,
           parent_versions.id AS existing_parent_id,
           current_assignment.version_id AS channel_version_id
    FROM builds
    LEFT JOIN versions AS parent_versions ON parent_versions.id = builds.parent_version_id
    LEFT JOIN channels AS parent_channels ON parent_channels.id = builds.parent_channel_id
    LEFT JOIN LATERAL (
        SELECT assignments.version_id
        FROM channel_assignments AS assignments
        WHERE assignments.channel_id = parent_channels.id
        ORDER BY assignments.assigned_at DESC, assignments.id DESC
        LIMIT 1
    ) AS current_assignment ON true
    WHERE builds.version_id = CAST($1 AS text)
      AND builds.parent_version_id IS NOT NULL
)
SELECT EXISTS (
           SELECT 1 FROM builds
           WHERE builds.parent_version_id = CAST($1 AS text)
       ) AS has_descendants,
       CASE
           WHEN NOT EXISTS (SELECT 1 FROM parents) THEN ''
           WHEN EXISTS (
               SELECT 1 FROM parents
               WHERE channel_version_id IS NOT NULL
                 AND channel_version_id <> parent_version_id
           ) THEN 'out_of_date'
           WHEN EXISTS (
               SELECT 1 FROM parents
               WHERE existing_parent_id IS NULL OR channel_version_id IS NULL
           ) THEN 'undetermined'
           ELSE 'up_to_date'
       END AS parents_status
`

type GetVersionRelationshipsRow struct {
	HasDescendants bool   `json:"has_descendants"`
	ParentsStatus  string `json:"parents_status"`
}

func (q *Queries) GetVersionRelationships(ctx context.Context, versionID string) (GetVersionRelationshipsRow, error) {
	row := q.db.QueryRowContext(ctx, getVersionRelationships, versionID)
	var i GetVersionRelationshipsRow
	err := row.Scan(&i.HasDescendants, &i.ParentsStatus)
	return i, err
}

const hasBlockingBagDropAssociations = `-- name: HasBlockingBagDropAssociations :one
SELECT EXISTS (
    SELECT 1 FROM bagdrop_associations
    WHERE state = 'pending_removal' OR first_attempted_at IS NOT NULL
)
`

func (q *Queries) HasBlockingBagDropAssociations(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasBlockingBagDropAssociations)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPin = `-- name: InsertPin :exec
INSERT INTO pins (organization_id, project_id, bucket_name, pinned_at, pinned_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertPinParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	BucketName     string    `json:"bucket_name"`
	PinnedAt       time.Time `json:"pinned_at"`
	PinnedBy       string    `json:"pinned_by"`
}

func (q *Queries) InsertPin(ctx context.Context, arg InsertPinParams) error {
	_, err := q.db.ExecContext(ctx, insertPin,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BucketName,
		arg.PinnedAt,
		arg.PinnedBy,
	)
	return err
}

const listArtifactsByBuild = `-- name: ListArtifactsByBuild :many
SELECT organization_id, project_id, id, build_id, external_identifier, region, created_at, integrity_mac FROM artifacts WHERE build_id = $1 ORDER BY id DESC
`

func (q *Queries) ListArtifactsByBuild(ctx context.Context, buildID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ProjectID,
			&i.ID,
			&i.BuildID,
			&i.ExternalIdentifier,
			&i.Region,
			&i.CreatedAt,
			&i.IntegrityMac,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditTargets = `-- name: ListAuditTargets :many
SELECT id, slot, path, created_at
FROM audit_targets
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAuditTargets(ctx context.Context) ([]AuditTarget, error) {
	rows, err := q.db.QueryContext(ctx, listAuditTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTarget
	for rows.Next() {
		var i AuditTarget
		if err := rows.Scan(
			&i.ID,
			&i.Slot,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBagDropAssociations = `-- name: ListBagDropAssociations :many
SELECT organization_id, project_id, bucket_name, state, first_attempted_at, last_synced_at, created_at, updated_at
FROM bagdrop_associations
ORDER BY created_at, bucket_name
`

func (q *Queries) ListBagDropAssociations(ctx context.Context) ([]BagdropAssociation, error) {
	rows, err := q.db.QueryContext(ctx, listBagDropAssociations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BagdropAssociation
	for rows.Next() {
		var i BagdropAssociation
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ProjectID,
			&i.BucketName,
			&i.State,
			&i.FirstAttemptedAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsByVersion = `-- name: ListBuildsByVersion :many
SELECT builds.organization_id, builds.project_id, builds.id, builds.version_id, builds.component_type, builds.status, builds.platform, builds.metadata_seen, builds.packer_run_uuid, builds.labels, builds.source_external_identifier, builds.created_at, builds.updated_at, builds.parent_version_id, builds.parent_channel_id, builds.metadata, builds.integrity_mac
FROM builds
JOIN versions ON versions.id = builds.version_id
JOIN buckets ON buckets.id = versions.bucket_id
WHERE buckets.name = $1 AND versions.fingerprint = $2
ORDER BY builds.id DESC
`

type ListBuildsByVersionParams struct {
	Name        string `json:"name"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) ListBuildsByVersion(ctx context.Context, arg ListBuildsByVersionParams) ([]Build, error) {
	rows, err := q.db.QueryContext(ctx, listBuildsByVersion, arg.Name, arg.Fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ProjectID,
			&i.ID,
			&i.VersionID,
			&i.ComponentType,
			&i.Status,
			&i.Platform,
			&i.MetadataSeen,
			&i.PackerRunUuid,
			&i.Labels,
			&i.SourceExternalIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentVersionID,
			&i.ParentChannelID,
			&i.Metadata,
			&i.IntegrityMac,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeyringEntries = `-- name: ListKeyringEntries :many
SELECT purpose, version, wrapped_key, kek_ref, created_at
FROM keyring
ORDER BY purpose, version
`

func (q *Queries) ListKeyringEntries(ctx context.Context) ([]Keyring, error) {
	rows, err := q.db.QueryContext(ctx, listKeyringEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keyring
	for rows.Next() {
		var i Keyring
		if err := rows.Scan(
			&i.Purpose,
			&i.Version,
			&i.WrappedKey,
			&i.KekRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, created_at
FROM organizations
ORDER BY created_at, id
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPins = `-- name: ListPins :many
SELECT bucket_name, pinned_at, pinned_by
FROM pins
ORDER BY pinned_at, bucket_name
`

type ListPinsRow struct {
	BucketName string    `json:"bucket_name"`
	PinnedAt   time.Time `json:"pinned_at"`
	PinnedBy   string    `json:"pinned_by"`
}

func (q *Queries) ListPins(ctx context.Context) ([]ListPinsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinsRow
	for rows.Next() {
		var i ListPinsRow
		if err := rows.Scan(&i.BucketName, &i.PinnedAt, &i.PinnedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformPrincipals = `-- name: ListPlatformPrincipals :many

SELECT id, name, client_id, organization_id, project_id, created_at, role, integrity_mac
FROM principals
WHERE organization_id IS NULL
ORDER BY created_at DESC, id DESC
`

// Principal listings select EXACTLY one scope, never a subtree: platform lists
// the platform principals, an organization lists its organization-scoped
// principals only, a project lists its own. See-where-you-stand and
// create-where-you-stand are the same rule (duf-4qr).
func (q *Queries) ListPlatformPrincipals(ctx context.Context) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Principal
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.Role,
			&i.IntegrityMac,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalSecrets = `-- name: ListPrincipalSecrets :many
SELECT id, principal_id, encoded_hash, created_at, last_used_at, integrity_mac, expires_at
FROM principal_secrets
WHERE principal_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPrincipalSecrets(ctx context.Context, principalID string) ([]PrincipalSecret, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipalSecrets, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrincipalSecret
	for rows.Next() {
		var i PrincipalSecret
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.EncodedHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.IntegrityMac,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalsByOrganization = `-- name: ListPrincipalsByOrganization :many
SELECT id, name, client_id, organization_id, project_id, created_at, role, integrity_mac
FROM principals
WHERE organization_id = $1 AND project_id IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPrincipalsByOrganization(ctx context.Context, organizationID uuid.NullUUID) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipalsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Principal
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.Role,
			&i.IntegrityMac,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalsByProject = `-- name: ListPrincipalsByProject :many
SELECT id, name, client_id, organization_id, project_id, created_at, role, integrity_mac
FROM principals
WHERE organization_id = $1 AND project_id = $2
ORDER BY created_at DESC, id DESC
`

type ListPrincipalsByProjectParams struct {
	OrganizationID uuid.NullUUID `json:"organization_id"`
	ProjectID      uuid.NullUUID `json:"project_id"`
}

func (q *Queries) ListPrincipalsByProject(ctx context.Context, arg ListPrincipalsByProjectParams) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipalsByProject, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Principal
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.Role,
			&i.IntegrityMac,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, organization_id, name, created_at
FROM projects
WHERE organization_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context, organizationID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionDescendants = `-- name: ListVersionDescendants :many
WITH RECURSIVE descendants(id) AS (
    SELECT builds.version_id FROM builds
    WHERE builds.parent_version_id = CAST($1 AS text)
    UNION
    SELECT builds.version_id FROM builds
    JOIN descendants ON builds.parent_version_id = descendants.id
)
SELECT versions.organization_id, versions.project_id, versions.id, versions.bucket_id, versions.fingerprint, versions.template_type, versions.complete, versions.sequence, versions.created_at, versions.updated_at, versions.author_id, versions.integrity_mac, versions.revoke_at, versions.revocation_message, versions.revocation_author, versions.revocation_inherited_from_id, versions.revocation_inherited_from_bucket, versions.revocation_inherited_from_fingerprint, versions.revocation_inherited_from_name, buckets.name AS bucket_name
FROM versions
JOIN descendants ON descendants.id = versions.id
JOIN buckets ON buckets.id = versions.bucket_id
ORDER BY versions.id
`

type ListVersionDescendantsRow struct {
	OrganizationID                     uuid.UUID      `json:"organization_id"`
	ProjectID                          uuid.UUID      `json:"project_id"`
	ID                                 string         `json:"id"`
	BucketID                           string         `json:"bucket_id"`
	Fingerprint                        string         `json:"fingerprint"`
	TemplateType                       string         `json:"template_type"`
	Complete                           bool           `json:"complete"`
	Sequence                           sql.NullInt32  `json:"sequence"`
	CreatedAt                          time.Time      `json:"created_at"`
	UpdatedAt                          time.Time      `json:"updated_at"`
	AuthorID                           string         `json:"author_id"`
	IntegrityMac                       []byte         `json:"integrity_mac"`
	RevokeAt                           sql.NullTime   `json:"revoke_at"`
	RevocationMessage                  sql.NullString `json:"revocation_message"`
	RevocationAuthor                   sql.NullString `json:"revocation_author"`
	RevocationInheritedFromID          sql.NullString `json:"revocation_inherited_from_id"`
	RevocationInheritedFromBucket      sql.NullString `json:"revocation_inherited_from_bucket"`
	RevocationInheritedFromFingerprint sql.NullString `json:"revocation_inherited_from_fingerprint"`
	RevocationInheritedFromName        sql.NullString `json:"revocation_inherited_from_name"`
	BucketName                         string         `json:"bucket_name"`
}

func (q *Queries) ListVersionDescendants(ctx context.Context, versionID string) ([]ListVersionDescendantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVersionDescendants, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionDescendantsRow
	for rows.Next() {
		var i ListVersionDescendantsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ProjectID,
			&i.ID,
			&i.BucketID,
			&i.Fingerprint,
			&i.TemplateType,
			&i.Complete,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.IntegrityMac,
			&i.RevokeAt,
			&i.RevocationMessage,
			&i.RevocationAuthor,
			&i.RevocationInheritedFromID,
			&i.RevocationInheritedFromBucket,
			&i.RevocationInheritedFromFingerprint,
			&i.RevocationInheritedFromName,
			&i.BucketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsByBucket = `-- name: ListVersionsByBucket :many
SELECT versions.organization_id, versions.project_id, versions.id, versions.bucket_id, versions.fingerprint, versions.template_type, versions.complete, versions.sequence, versions.created_at, versions.updated_at, versions.author_id, versions.integrity_mac, versions.revoke_at, versions.revocation_message, versions.revocation_author, versions.revocation_inherited_from_id, versions.revocation_inherited_from_bucket, versions.revocation_inherited_from_fingerprint, versions.revocation_inherited_from_name, buckets.name AS bucket_name
FROM versions
JOIN buckets ON buckets.id = versions.bucket_id
WHERE buckets.name = $1
ORDER BY versions.sequence DESC, versions.created_at DESC
`

type ListVersionsByBucketRow struct {
	OrganizationID                     uuid.UUID      `json:"organization_id"`
	ProjectID                          uuid.UUID      `json:"project_id"`
	ID                                 string         `json:"id"`
	BucketID                           string         `json:"bucket_id"`
	Fingerprint                        string         `json:"fingerprint"`
	TemplateType                       string         `json:"template_type"`
	Complete                           bool           `json:"complete"`
	Sequence                           sql.NullInt32  `json:"sequence"`
	CreatedAt                          time.Time      `json:"created_at"`
	UpdatedAt                          time.Time      `json:"updated_at"`
	AuthorID                           string         `json:"author_id"`
	IntegrityMac                       []byte         `json:"integrity_mac"`
	RevokeAt                           sql.NullTime   `json:"revoke_at"`
	RevocationMessage                  sql.NullString `json:"revocation_message"`
	RevocationAuthor                   sql.NullString `json:"revocation_author"`
	RevocationInheritedFromID          sql.NullString `json:"revocation_inherited_from_id"`
	RevocationInheritedFromBucket      sql.NullString `json:"revocation_inherited_from_bucket"`
	RevocationInheritedFromFingerprint sql.NullString `json:"revocation_inherited_from_fingerprint"`
	RevocationInheritedFromName        sql.NullString `json:"revocation_inherited_from_name"`
	BucketName                         string         `json:"bucket_name"`
}

func (q *Queries) ListVersionsByBucket(ctx context.Context, name string) ([]ListVersionsByBucketRow, error) {
	rows, err := q.db.QueryContext(ctx, listVersionsByBucket, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionsByBucketRow
	for rows.Next() {
		var i ListVersionsByBucketRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ProjectID,
			&i.ID,
			&i.BucketID,
			&i.Fingerprint,
			&i.TemplateType,
			&i.Complete,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.IntegrityMac,
			&i.RevokeAt,
			&i.RevocationMessage,
			&i.RevocationAuthor,
			&i.RevocationInheritedFromID,
			&i.RevocationInheritedFromBucket,
			&i.RevocationInheritedFromFingerprint,
			&i.RevocationInheritedFromName,
			&i.BucketName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAuditTargetSlots = `-- name: LockAuditTargetSlots :exec
SELECT pg_advisory_xact_lock(1646664800)
`

// Serializes lowest-free-slot selection so two concurrent creates cannot read
// the same free slot and have one fail on UNIQUE. Held for the transaction,
// which does nothing but this insert.
func (q *Queries) LockAuditTargetSlots(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockAuditTargetSlots)
	return err
}

const lockBucketForVersionSequence = `-- name: LockBucketForVersionSequence :one
SELECT id FROM buckets WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockBucketForVersionSequence(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockBucketForVersionSequence, id)
	err := row.Scan(&id)
	return id, err
}

const lockInitialization = `-- name: LockInitialization :exec
LOCK TABLE instance IN EXCLUSIVE MODE
`

func (q *Queries) LockInitialization(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockInitialization)
	return err
}

const lockRootPrincipalDeletion = `-- name: LockRootPrincipalDeletion :exec
SELECT pg_advisory_xact_lock(1646664799)
`

// Serializes the root count-and-delete decision across transactions and server
// instances. The fixed key is private to this database and this invariant.
func (q *Queries) LockRootPrincipalDeletion(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockRootPrincipalDeletion)
	return err
}

const nextVersionSequence = `-- name: NextVersionSequence :one
SELECT coalesce(max(sequence), 0)::integer + 1
FROM versions
WHERE bucket_id = $1
`

func (q *Queries) NextVersionSequence(ctx context.Context, bucketID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextVersionSequence, bucketID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const recordBagDropVerification = `-- name: RecordBagDropVerification :one
UPDATE bagdrop_configs
SET last_verification = $1, last_verified_at = $2, updated_at = $2
RETURNING organization_id, project_id, adapter, destination, sealed_secret, enabled, last_verification, last_verified_at, created_at, updated_at
`

type RecordBagDropVerificationParams struct {
	LastVerification []byte       `json:"last_verification"`
	LastVerifiedAt   sql.NullTime `json:"last_verified_at"`
}

func (q *Queries) RecordBagDropVerification(ctx context.Context, arg RecordBagDropVerificationParams) (BagdropConfig, error) {
	row := q.db.QueryRowContext(ctx, recordBagDropVerification, arg.LastVerification, arg.LastVerifiedAt)
	var i BagdropConfig
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.Adapter,
		&i.Destination,
		&i.SealedSecret,
		&i.Enabled,
		&i.LastVerification,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordEncryptionMode = `-- name: RecordEncryptionMode :execrows
INSERT INTO encryption_mode (id, encrypted, recorded_at)
VALUES (true, $1, $2)
ON CONFLICT (id) DO NOTHING
`

type RecordEncryptionModeParams struct {
	Encrypted  bool      `json:"encrypted"`
	RecordedAt time.Time `json:"recorded_at"`
}

func (q *Queries) RecordEncryptionMode(ctx context.Context, arg RecordEncryptionModeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordEncryptionMode, arg.Encrypted, arg.RecordedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordInitialization = `-- name: RecordInitialization :exec
INSERT INTO instance (id, initialized_at, recovery_digest, recovery_threshold)
VALUES (true, $1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type RecordInitializationParams struct {
	InitializedAt     time.Time     `json:"initialized_at"`
	RecoveryDigest    []byte        `json:"recovery_digest"`
	RecoveryThreshold sql.NullInt32 `json:"recovery_threshold"`
}

func (q *Queries) RecordInitialization(ctx context.Context, arg RecordInitializationParams) error {
	_, err := q.db.ExecContext(ctx, recordInitialization, arg.InitializedAt, arg.RecoveryDigest, arg.RecoveryThreshold)
	return err
}

const removeBagDropAssociation = `-- name: RemoveBagDropAssociation :one
WITH hard_deleted AS (
    DELETE FROM bagdrop_associations
    WHERE bagdrop_associations.bucket_name = $1
      AND bagdrop_associations.first_attempted_at IS NULL
    RETURNING bagdrop_associations.bucket_name
), pending AS (
    UPDATE bagdrop_associations
    SET state = 'pending_removal', updated_at = $2
    WHERE bagdrop_associations.bucket_name = $1
      AND bagdrop_associations.first_attempted_at IS NOT NULL
    RETURNING bagdrop_associations.bucket_name
)
SELECT CASE
    WHEN EXISTS (SELECT 1 FROM pending) THEN 'removal_pending'
    ELSE 'removed_clean'
END AS outcome
`

type RemoveBagDropAssociationParams struct {
	BucketName string    `json:"bucket_name"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) RemoveBagDropAssociation(ctx context.Context, arg RemoveBagDropAssociationParams) (string, error) {
	row := q.db.QueryRowContext(ctx, removeBagDropAssociation, arg.BucketName, arg.UpdatedAt)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const revokeVersion = `-- name: RevokeVersion :one
UPDATE versions
SET revoke_at = $2, revocation_message = $3, revocation_author = $4,
    revocation_inherited_from_id = $5, revocation_inherited_from_bucket = $6,
    revocation_inherited_from_fingerprint = $7, revocation_inherited_from_name = $8,
    updated_at = $9
WHERE id = $1 AND revoke_at IS NULL
RETURNING organization_id, project_id, id, bucket_id, fingerprint, template_type, complete, sequence, created_at, updated_at, author_id, integrity_mac, revoke_at, revocation_message, revocation_author, revocation_inherited_from_id, revocation_inherited_from_bucket, revocation_inherited_from_fingerprint, revocation_inherited_from_name
`

type RevokeVersionParams struct {
	ID                                 string         `json:"id"`
	RevokeAt                           sql.NullTime   `json:"revoke_at"`
	RevocationMessage                  sql.NullString `json:"revocation_message"`
	RevocationAuthor                   sql.NullString `json:"revocation_author"`
	RevocationInheritedFromID          sql.NullString `json:"revocation_inherited_from_id"`
	RevocationInheritedFromBucket      sql.NullString `json:"revocation_inherited_from_bucket"`
	RevocationInheritedFromFingerprint sql.NullString `json:"revocation_inherited_from_fingerprint"`
	RevocationInheritedFromName        sql.NullString `json:"revocation_inherited_from_name"`
	UpdatedAt                          time.Time      `json:"updated_at"`
}

func (q *Queries) RevokeVersion(ctx context.Context, arg RevokeVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, revokeVersion,
		arg.ID,
		arg.RevokeAt,
		arg.RevocationMessage,
		arg.RevocationAuthor,
		arg.RevocationInheritedFromID,
		arg.RevocationInheritedFromBucket,
		arg.RevocationInheritedFromFingerprint,
		arg.RevocationInheritedFromName,
		arg.UpdatedAt,
	)
	var i Version
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.BucketID,
		&i.Fingerprint,
		&i.TemplateType,
		&i.Complete,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.IntegrityMac,
		&i.RevokeAt,
		&i.RevocationMessage,
		&i.RevocationAuthor,
		&i.RevocationInheritedFromID,
		&i.RevocationInheritedFromBucket,
		&i.RevocationInheritedFromFingerprint,
		&i.RevocationInheritedFromName,
	)
	return i, err
}

const rewrapKeyringEntry = `-- name: RewrapKeyringEntry :execrows
UPDATE keyring
SET wrapped_key = $3, kek_ref = $4, created_at = $5
WHERE purpose = $1 AND version = $2
`

type RewrapKeyringEntryParams struct {
	Purpose    string    `json:"purpose"`
	Version    int32     `json:"version"`
	WrappedKey []byte    `json:"wrapped_key"`
	KekRef     string    `json:"kek_ref"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) RewrapKeyringEntry(ctx context.Context, arg RewrapKeyringEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rewrapKeyringEntry,
		arg.Purpose,
		arg.Version,
		arg.WrappedKey,
		arg.KekRef,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rootPrincipalExists = `-- name: RootPrincipalExists :one
SELECT EXISTS (
    SELECT 1
    FROM principals
    WHERE role = 'root'
      AND organization_id IS NULL
      AND project_id IS NULL
) AS initialized
`

func (q *Queries) RootPrincipalExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, rootPrincipalExists)
	var initialized bool
	err := row.Scan(&initialized)
	return initialized, err
}

const setArtifactIntegrityMAC = `-- name: SetArtifactIntegrityMAC :exec
UPDATE artifacts SET integrity_mac = $2 WHERE id = $1
`

type SetArtifactIntegrityMACParams struct {
	ID           string `json:"id"`
	IntegrityMac []byte `json:"integrity_mac"`
}

func (q *Queries) SetArtifactIntegrityMAC(ctx context.Context, arg SetArtifactIntegrityMACParams) error {
	_, err := q.db.ExecContext(ctx, setArtifactIntegrityMAC, arg.ID, arg.IntegrityMac)
	return err
}

const setBuildIntegrityMAC = `-- name: SetBuildIntegrityMAC :exec
UPDATE builds SET integrity_mac = $2 WHERE id = $1
`

type SetBuildIntegrityMACParams struct {
	ID           string `json:"id"`
	IntegrityMac []byte `json:"integrity_mac"`
}

func (q *Queries) SetBuildIntegrityMAC(ctx context.Context, arg SetBuildIntegrityMACParams) error {
	_, err := q.db.ExecContext(ctx, setBuildIntegrityMAC, arg.ID, arg.IntegrityMac)
	return err
}

const setVersionIntegrityMAC = `-- name: SetVersionIntegrityMAC :exec
UPDATE versions SET integrity_mac = $2 WHERE id = $1
`

type SetVersionIntegrityMACParams struct {
	ID           string `json:"id"`
	IntegrityMac []byte `json:"integrity_mac"`
}

func (q *Queries) SetVersionIntegrityMAC(ctx context.Context, arg SetVersionIntegrityMACParams) error {
	_, err := q.db.ExecContext(ctx, setVersionIntegrityMAC, arg.ID, arg.IntegrityMac)
	return err
}

const touchSecretLastUsed = `-- name: TouchSecretLastUsed :exec
UPDATE principal_secrets SET last_used_at = $2 WHERE id = $1
`

type TouchSecretLastUsedParams struct {
	ID         string       `json:"id"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
}

// last_used_at is not part of principalSecretMACMessage, so this metadata-only
// update does not require re-sealing the secret row.
func (q *Queries) TouchSecretLastUsed(ctx context.Context, arg TouchSecretLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchSecretLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const updateBucket = `-- name: UpdateBucket :one
UPDATE buckets
SET description = $2, labels = $3, updated_at = $4
WHERE name = $1
RETURNING organization_id, project_id, id, name, description, labels, created_at, updated_at
`

type UpdateBucketParams struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Labels      json.RawMessage `json:"labels"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateBucket(ctx context.Context, arg UpdateBucketParams) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, updateBucket,
		arg.Name,
		arg.Description,
		arg.Labels,
		arg.UpdatedAt,
	)
	var i Bucket
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBuild = `-- name: UpdateBuild :one
UPDATE builds
SET status = $4,
    platform = $5,
    metadata_seen = $6,
    packer_run_uuid = $7,
    labels = $8,
    source_external_identifier = $9,
    parent_version_id = $10,
    parent_channel_id = $11,
    metadata = $12,
    updated_at = CASE
        WHEN ROW(status, platform, metadata_seen, packer_run_uuid, labels, source_external_identifier,
                 parent_version_id, parent_channel_id, metadata)
             IS DISTINCT FROM ROW($4, $5, $6, $7, $8, $9, $10, $11, $12)
        THEN $13
        ELSE updated_at
    END
WHERE id = $3 AND organization_id = $1 AND project_id = $2
RETURNING organization_id, project_id, id, version_id, component_type, status, platform, metadata_seen, packer_run_uuid, labels, source_external_identifier, created_at, updated_at, parent_version_id, parent_channel_id, metadata, integrity_mac
`

type UpdateBuildParams struct {
	OrganizationID           uuid.UUID       `json:"organization_id"`
	ProjectID                uuid.UUID       `json:"project_id"`
	ID                       string          `json:"id"`
	Status                   string          `json:"status"`
	Platform                 string          `json:"platform"`
	MetadataSeen             bool            `json:"metadata_seen"`
	PackerRunUuid            string          `json:"packer_run_uuid"`
	Labels                   json.RawMessage `json:"labels"`
	SourceExternalIdentifier string          `json:"source_external_identifier"`
	ParentVersionID          sql.NullString  `json:"parent_version_id"`
	ParentChannelID          sql.NullString  `json:"parent_channel_id"`
	Metadata                 []byte          `json:"metadata"`
	UpdatedAt                time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (Build, error) {
	row := q.db.QueryRowContext(ctx, updateBuild,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ID,
		arg.Status,
		arg.Platform,
		arg.MetadataSeen,
		arg.PackerRunUuid,
		arg.Labels,
		arg.SourceExternalIdentifier,
		arg.ParentVersionID,
		arg.ParentChannelID,
		arg.Metadata,
		arg.UpdatedAt,
	)
	var i Build
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.VersionID,
		&i.ComponentType,
		&i.Status,
		&i.Platform,
		&i.MetadataSeen,
		&i.PackerRunUuid,
		&i.Labels,
		&i.SourceExternalIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentVersionID,
		&i.ParentChannelID,
		&i.Metadata,
		&i.IntegrityMac,
	)
	return i, err
}

const upsertBagDropAssociation = `-- name: UpsertBagDropAssociation :one
INSERT INTO bagdrop_associations (
    organization_id, project_id, bucket_name, state, first_attempted_at,
    last_synced_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (organization_id, project_id, bucket_name) DO UPDATE SET
    state = EXCLUDED.state,
    first_attempted_at = COALESCE(
        bagdrop_associations.first_attempted_at, EXCLUDED.first_attempted_at
    ),
    last_synced_at = COALESCE(
        bagdrop_associations.last_synced_at, EXCLUDED.last_synced_at
    ),
    updated_at = CASE
        WHEN bagdrop_associations.state <> EXCLUDED.state THEN EXCLUDED.updated_at
        ELSE bagdrop_associations.updated_at
    END
RETURNING organization_id, project_id, bucket_name, state, first_attempted_at, last_synced_at, created_at, updated_at
`

type UpsertBagDropAssociationParams struct {
	OrganizationID   uuid.UUID    `json:"organization_id"`
	ProjectID        uuid.UUID    `json:"project_id"`
	BucketName       string       `json:"bucket_name"`
	State            string       `json:"state"`
	FirstAttemptedAt sql.NullTime `json:"first_attempted_at"`
	LastSyncedAt     sql.NullTime `json:"last_synced_at"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertBagDropAssociation(ctx context.Context, arg UpsertBagDropAssociationParams) (BagdropAssociation, error) {
	row := q.db.QueryRowContext(ctx, upsertBagDropAssociation,
		arg.OrganizationID,
		arg.ProjectID,
		arg.BucketName,
		arg.State,
		arg.FirstAttemptedAt,
		arg.LastSyncedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BagdropAssociation
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.BucketName,
		&i.State,
		&i.FirstAttemptedAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBagDropConfig = `-- name: UpsertBagDropConfig :one
INSERT INTO bagdrop_configs (
    organization_id, project_id, adapter, destination, sealed_secret, enabled,
    last_verification, last_verified_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (organization_id, project_id) DO UPDATE SET
    adapter = EXCLUDED.adapter,
    destination = EXCLUDED.destination,
    sealed_secret = EXCLUDED.sealed_secret,
    enabled = EXCLUDED.enabled,
    last_verification = EXCLUDED.last_verification,
    last_verified_at = EXCLUDED.last_verified_at,
    updated_at = EXCLUDED.updated_at
RETURNING organization_id, project_id, adapter, destination, sealed_secret, enabled, last_verification, last_verified_at, created_at, updated_at
`

type UpsertBagDropConfigParams struct {
	OrganizationID   uuid.UUID       `json:"organization_id"`
	ProjectID        uuid.UUID       `json:"project_id"`
	Adapter          string          `json:"adapter"`
	Destination      json.RawMessage `json:"destination"`
	SealedSecret     []byte          `json:"sealed_secret"`
	Enabled          bool            `json:"enabled"`
	LastVerification []byte          `json:"last_verification"`
	LastVerifiedAt   sql.NullTime    `json:"last_verified_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

func (q *Queries) UpsertBagDropConfig(ctx context.Context, arg UpsertBagDropConfigParams) (BagdropConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertBagDropConfig,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Adapter,
		arg.Destination,
		arg.SealedSecret,
		arg.Enabled,
		arg.LastVerification,
		arg.LastVerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BagdropConfig
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.Adapter,
		&i.Destination,
		&i.SealedSecret,
		&i.Enabled,
		&i.LastVerification,
		&i.LastVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSbom = `-- name: UpsertSbom :one
INSERT INTO sboms (
    organization_id, project_id, id, build_id, name, format, object_key, created_at
)
SELECT $1, $2, $3, builds.id, $7, $8, $9, $10
FROM builds
JOIN versions ON versions.id = builds.version_id
JOIN buckets ON buckets.id = versions.bucket_id
WHERE buckets.name = $4 AND versions.fingerprint = $5 AND builds.id = $6
ON CONFLICT (organization_id, project_id, build_id, name)
DO UPDATE SET format = EXCLUDED.format, object_key = EXCLUDED.object_key
RETURNING organization_id, project_id, id, build_id, name, format,
          object_key, created_at, parse_status, parse_error
`

type UpsertSbomParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Fingerprint    string    `json:"fingerprint"`
	ID_2           string    `json:"id_2"`
	Name_2         string    `json:"name_2"`
	Format         string    `json:"format"`
	ObjectKey      string    `json:"object_key"`
	CreatedAt      time.Time `json:"created_at"`
}

type UpsertSbomRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	ID             string    `json:"id"`
	BuildID        string    `json:"build_id"`
	Name           string    `json:"name"`
	Format         string    `json:"format"`
	ObjectKey      string    `json:"object_key"`
	CreatedAt      time.Time `json:"created_at"`
	ParseStatus    string    `json:"parse_status"`
	ParseError     string    `json:"parse_error"`
}

func (q *Queries) UpsertSbom(ctx context.Context, arg UpsertSbomParams) (UpsertSbomRow, error) {
	row := q.db.QueryRowContext(ctx, upsertSbom,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Fingerprint,
		arg.ID_2,
		arg.Name_2,
		arg.Format,
		arg.ObjectKey,
		arg.CreatedAt,
	)
	var i UpsertSbomRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.ID,
		&i.BuildID,
		&i.Name,
		&i.Format,
		&i.ObjectKey,
		&i.CreatedAt,
		&i.ParseStatus,
		&i.ParseError,
	)
	return i, err
}
