apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dufflebag.fullname" . }}-postgres
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.adminPassword | quote }}
  app-password: {{ .Values.postgres.appPassword | quote }}
  app-database-url: {{ printf "postgres://dufflebag:%s@%s-postgres:5432/dufflebag?sslmode=disable" .Values.postgres.appPassword (include "dufflebag.fullname" .) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dufflebag.fullname" . }}-ceph
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.ceph.accessKey | quote }}
  secret-key: {{ .Values.ceph.secretKey | quote }}
