apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dufflebag.fullname" . }}
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dufflebag.fullname" . }}-vault
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dufflebag.fullname" . }}-vault-bootstrap
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s-vault-reviewer" .Release.Namespace (include "dufflebag.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ include "dufflebag.fullname" . }}-vault
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dufflebag.fullname" . }}-vault-bootstrap
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ printf "%s-vault-bootstrap" (include "dufflebag.fullname" .) | quote }}]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dufflebag.fullname" . }}-vault-bootstrap
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dufflebag.fullname" . }}-vault-bootstrap
subjects:
  - kind: ServiceAccount
    name: {{ include "dufflebag.fullname" . }}-vault-bootstrap
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dufflebag.fullname" . }}-ceph
  labels:
    {{- include "dufflebag.labels" . | nindent 4 }}
