// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudResourcemanagerResourceSetIamPolicyResponse ResourceSetIamPolicyResponse see ResourceService.SetIamPolicy
//
// swagger:model hashicorp.cloud.resourcemanager.ResourceSetIamPolicyResponse
type HashicorpCloudResourcemanagerResourceSetIamPolicyResponse struct {

	// Policy is the updated IAM policy for the resource.
	Policy *HashicorpCloudResourcemanagerPolicy `json:"policy,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager resource set iam policy response
func (m *HashicorpCloudResourcemanagerResourceSetIamPolicyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudResourcemanagerResourceSetIamPolicyResponse) validatePolicy(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Policy) { // not required
		return nil
	}

	if m.Policy != nil {
		if err := m.Policy.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("policy")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("policy")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud resourcemanager resource set iam policy response based on the context it is used
func (m *HashicorpCloudResourcemanagerResourceSetIamPolicyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudResourcemanagerResourceSetIamPolicyResponse) contextValidatePolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.Policy != nil {

		if typeutils.IsZero(m.Policy) { // not required
			return nil
		}

		if err := m.Policy.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("policy")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("policy")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerResourceSetIamPolicyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerResourceSetIamPolicyResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerResourceSetIamPolicyResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
