// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerOrganizationServiceSetNameBody see OrganizationService.SetName
//
// swagger:model hashicorp.cloud.resourcemanager.OrganizationService.SetNameBody
type HashicorpCloudResourcemanagerOrganizationServiceSetNameBody struct {

	// Name is the new name of the organization.
	Name string `json:"name,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager organization service set name body
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetNameBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager organization service set name body based on context it is used
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetNameBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetNameBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetNameBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerOrganizationServiceSetNameBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
