// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerServicePrincipalDetail ServicePrincipalDetail provides information about a service principal causing a failure.
//
// swagger:model hashicorp.cloud.resourcemanager.ServicePrincipalDetail
type HashicorpCloudResourcemanagerServicePrincipalDetail struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organization id
	OrganizationID string `json:"organization_id,omitempty"`

	// project id
	ProjectID string `json:"project_id,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager service principal detail
func (m *HashicorpCloudResourcemanagerServicePrincipalDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager service principal detail based on context it is used
func (m *HashicorpCloudResourcemanagerServicePrincipalDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerServicePrincipalDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerServicePrincipalDetail) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerServicePrincipalDetail
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
