// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerOrganizationServiceTestIamPermissionsBody see OrganizationService.TestIamPermissions
//
// swagger:model hashicorp.cloud.resourcemanager.OrganizationService.TestIamPermissionsBody
type HashicorpCloudResourcemanagerOrganizationServiceTestIamPermissionsBody struct {

	// Permissions to test.
	Permissions []string `json:"permissions"`
}

// Validate validates this hashicorp cloud resourcemanager organization service test iam permissions body
func (m *HashicorpCloudResourcemanagerOrganizationServiceTestIamPermissionsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager organization service test iam permissions body based on context it is used
func (m *HashicorpCloudResourcemanagerOrganizationServiceTestIamPermissionsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationServiceTestIamPermissionsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationServiceTestIamPermissionsBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerOrganizationServiceTestIamPermissionsBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
