// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerProjectServiceSetNameBody ProjectSetNameRequest see ProjectService.SetName
//
// swagger:model hashicorp.cloud.resourcemanager.ProjectService.SetNameBody
type HashicorpCloudResourcemanagerProjectServiceSetNameBody struct {

	// name is the value the project's name should be updated to.
	Name string `json:"name,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager project service set name body
func (m *HashicorpCloudResourcemanagerProjectServiceSetNameBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager project service set name body based on context it is used
func (m *HashicorpCloudResourcemanagerProjectServiceSetNameBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerProjectServiceSetNameBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerProjectServiceSetNameBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerProjectServiceSetNameBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
