// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudResourcemanagerOrganizationOwnershipDetailsPersonalOwnership hashicorp cloud resourcemanager organization ownership details personal ownership
//
// swagger:model hashicorp.cloud.resourcemanager.OrganizationOwnershipDetails.PersonalOwnership
type HashicorpCloudResourcemanagerOrganizationOwnershipDetailsPersonalOwnership any
