// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerOrganizationServiceSetResourceControlPolicyBody SetResourceControlPolicyRequest see OrganizationService.SetResourceControlPolicy
//
// swagger:model hashicorp.cloud.resourcemanager.OrganizationService.SetResourceControlPolicyBody
type HashicorpCloudResourcemanagerOrganizationServiceSetResourceControlPolicyBody struct {

	// Array of contraint_ids referencing constraints.id
	ConstraintIds []string `json:"constraint_ids"`

	// Etag identifies this version of the policy.
	Etag string `json:"etag,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager organization service set resource control policy body
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetResourceControlPolicyBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager organization service set resource control policy body based on context it is used
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetResourceControlPolicyBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetResourceControlPolicyBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationServiceSetResourceControlPolicyBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerOrganizationServiceSetResourceControlPolicyBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
