// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerSetResourceControlPolicyResponse SetResourceControlPolicyResponse see OrganizationService.SetResourceControlPolicy
//
// swagger:model hashicorp.cloud.resourcemanager.SetResourceControlPolicyResponse
type HashicorpCloudResourcemanagerSetResourceControlPolicyResponse struct {

	// Etag identifies this version of the policy.
	Etag string `json:"etag,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager set resource control policy response
func (m *HashicorpCloudResourcemanagerSetResourceControlPolicyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager set resource control policy response based on context it is used
func (m *HashicorpCloudResourcemanagerSetResourceControlPolicyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerSetResourceControlPolicyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerSetResourceControlPolicyResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerSetResourceControlPolicyResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
