// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerOrganizationTestIamPermissionsResponse see OrganizationService.TestIamPermissions
//
// swagger:model hashicorp.cloud.resourcemanager.OrganizationTestIamPermissionsResponse
type HashicorpCloudResourcemanagerOrganizationTestIamPermissionsResponse struct {

	// AllowedPermissions are a subset of the request permissions the calling principal has for the organization.
	AllowedPermissions []string `json:"allowed_permissions"`
}

// Validate validates this hashicorp cloud resourcemanager organization test iam permissions response
func (m *HashicorpCloudResourcemanagerOrganizationTestIamPermissionsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager organization test iam permissions response based on context it is used
func (m *HashicorpCloudResourcemanagerOrganizationTestIamPermissionsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationTestIamPermissionsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationTestIamPermissionsResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerOrganizationTestIamPermissionsResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
