// Code generated by go-swagger; DO NOT EDIT.

package models

// HashicorpCloudResourcemanagerOrganizationDeleteResponse see OrganizationService.Delete
//
// swagger:model hashicorp.cloud.resourcemanager.OrganizationDeleteResponse
type HashicorpCloudResourcemanagerOrganizationDeleteResponse any
