// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerProjectServiceTestIamPermissionsBody see ProjectService.TestIamPermissions
//
// swagger:model hashicorp.cloud.resourcemanager.ProjectService.TestIamPermissionsBody
type HashicorpCloudResourcemanagerProjectServiceTestIamPermissionsBody struct {

	// Permissions to test.
	Permissions []string `json:"permissions"`
}

// Validate validates this hashicorp cloud resourcemanager project service test iam permissions body
func (m *HashicorpCloudResourcemanagerProjectServiceTestIamPermissionsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager project service test iam permissions body based on context it is used
func (m *HashicorpCloudResourcemanagerProjectServiceTestIamPermissionsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerProjectServiceTestIamPermissionsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerProjectServiceTestIamPermissionsBody) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerProjectServiceTestIamPermissionsBody
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
