// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// HashicorpCloudResourcemanagerOrganizationGetConstraintResponse OrganizationGetConstraintResponse see GetConstraint
//
// swagger:model hashicorp.cloud.resourcemanager.OrganizationGetConstraintResponse
type HashicorpCloudResourcemanagerOrganizationGetConstraintResponse struct {

	// Constraint is the constraint that was requested.
	Constraint *HashicorpCloudResourcemanagerConstraint `json:"constraint,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager organization get constraint response
func (m *HashicorpCloudResourcemanagerOrganizationGetConstraintResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConstraint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudResourcemanagerOrganizationGetConstraintResponse) validateConstraint(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Constraint) { // not required
		return nil
	}

	if m.Constraint != nil {
		if err := m.Constraint.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("constraint")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("constraint")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this hashicorp cloud resourcemanager organization get constraint response based on the context it is used
func (m *HashicorpCloudResourcemanagerOrganizationGetConstraintResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConstraint(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HashicorpCloudResourcemanagerOrganizationGetConstraintResponse) contextValidateConstraint(ctx context.Context, formats strfmt.Registry) error {

	if m.Constraint != nil {

		if typeutils.IsZero(m.Constraint) { // not required
			return nil
		}

		if err := m.Constraint.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("constraint")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("constraint")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationGetConstraintResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerOrganizationGetConstraintResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerOrganizationGetConstraintResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
