// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// HashicorpCloudResourcemanagerProjectGetProjectsCountResponse ProjectGetProjectsCountResponse see ProjectService.GetProjectsCount
//
// swagger:model hashicorp.cloud.resourcemanager.ProjectGetProjectsCountResponse
type HashicorpCloudResourcemanagerProjectGetProjectsCountResponse struct {

	// Count is the count of projects belonging to a parent scope.
	Count int32 `json:"count,omitempty"`
}

// Validate validates this hashicorp cloud resourcemanager project get projects count response
func (m *HashicorpCloudResourcemanagerProjectGetProjectsCountResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hashicorp cloud resourcemanager project get projects count response based on context it is used
func (m *HashicorpCloudResourcemanagerProjectGetProjectsCountResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerProjectGetProjectsCountResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HashicorpCloudResourcemanagerProjectGetProjectsCountResponse) UnmarshalBinary(b []byte) error {
	var res HashicorpCloudResourcemanagerProjectGetProjectsCountResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
